[package]
name = "utxo-core"
version = "0.1.0"
edition = "2024"

[dependencies]
chain-core = { workspace = true }
bitcoin = { workspace = true }
bech32 = { workspace = true }
hex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
