[package]
name = "jamsrpay-proto"
version = "0.1.0"
edition = "2024"

[dependencies]
pbjson-types = "0.9.0"
prost = "0.14.4"
prost-types = "0.14.4"
serde = { version = "1.0", features = ["derive"] }
tonic = "0.14"
tonic-prost = "0.14"

[features]
default = []
full = [
    "asset",
    "billing",
    "blockchain",
    "identity",
    "indexer",
    "payout",
    "realtime",
    "shared",
    "store",
    "support",
    "user",
    "verification",
    "wallet",
    "webhook",
]
asset = ["shared"]
billing = ["shared", "asset"]
blockchain = ["shared"]
identity = ["shared"]
indexer = ["shared"]
payout = ["shared", "asset", "billing"]
realtime = ["shared"]
shared = []
store = ["shared", "asset", "billing", "payout"]
support = ["shared"]
user = ["shared"]
verification = ["shared"]
wallet = ["shared", "asset", "billing"]
webhook = ["shared"]
