// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AssetEnabled {
    #[prost(enumeration = "super::super::shared::v1::AssetId", tag = "1")]
    pub asset_id: i32,
}
impl ::prost::Name for AssetEnabled {
    const NAME: &'static str = "AssetEnabled";
    const PACKAGE: &'static str = "asset.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "asset.events.v1.AssetEnabled".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/asset.events.v1.AssetEnabled".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AssetDisabled {
    #[prost(enumeration = "super::super::shared::v1::AssetId", tag = "1")]
    pub asset_id: i32,
}
impl ::prost::Name for AssetDisabled {
    const NAME: &'static str = "AssetDisabled";
    const PACKAGE: &'static str = "asset.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "asset.events.v1.AssetDisabled".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/asset.events.v1.AssetDisabled".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BlockchainNetworkEnabled {
    #[prost(enumeration = "super::super::shared::v1::NetworkId", tag = "1")]
    pub network_id: i32,
}
impl ::prost::Name for BlockchainNetworkEnabled {
    const NAME: &'static str = "BlockchainNetworkEnabled";
    const PACKAGE: &'static str = "asset.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "asset.events.v1.BlockchainNetworkEnabled".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/asset.events.v1.BlockchainNetworkEnabled".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BlockchainNetworkDisabled {
    #[prost(enumeration = "super::super::shared::v1::NetworkId", tag = "1")]
    pub network_id: i32,
}
impl ::prost::Name for BlockchainNetworkDisabled {
    const NAME: &'static str = "BlockchainNetworkDisabled";
    const PACKAGE: &'static str = "asset.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "asset.events.v1.BlockchainNetworkDisabled".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/asset.events.v1.BlockchainNetworkDisabled".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AssetNetworkEnabled {
    #[prost(string, tag = "1")]
    pub asset_network_id: ::prost::alloc::string::String,
}
impl ::prost::Name for AssetNetworkEnabled {
    const NAME: &'static str = "AssetNetworkEnabled";
    const PACKAGE: &'static str = "asset.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "asset.events.v1.AssetNetworkEnabled".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/asset.events.v1.AssetNetworkEnabled".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AssetNetworkDisabled {
    #[prost(string, tag = "1")]
    pub asset_network_id: ::prost::alloc::string::String,
}
impl ::prost::Name for AssetNetworkDisabled {
    const NAME: &'static str = "AssetNetworkDisabled";
    const PACKAGE: &'static str = "asset.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "asset.events.v1.AssetNetworkDisabled".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/asset.events.v1.AssetNetworkDisabled".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FiatCurrencyEnabled {
    #[prost(enumeration = "super::super::shared::v1::FiatCurrencyId", tag = "1")]
    pub fiat_currency_id: i32,
}
impl ::prost::Name for FiatCurrencyEnabled {
    const NAME: &'static str = "FiatCurrencyEnabled";
    const PACKAGE: &'static str = "asset.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "asset.events.v1.FiatCurrencyEnabled".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/asset.events.v1.FiatCurrencyEnabled".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FiatCurrencyDisabled {
    #[prost(enumeration = "super::super::shared::v1::FiatCurrencyId", tag = "1")]
    pub fiat_currency_id: i32,
}
impl ::prost::Name for FiatCurrencyDisabled {
    const NAME: &'static str = "FiatCurrencyDisabled";
    const PACKAGE: &'static str = "asset.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "asset.events.v1.FiatCurrencyDisabled".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/asset.events.v1.FiatCurrencyDisabled".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AssetEventEnvelope {
    #[prost(message, optional, tag = "1")]
    pub meta: ::core::option::Option<
        super::super::super::shared::events::v1::EventMetadata,
    >,
    #[prost(oneof = "asset_event_envelope::Event", tags = "2, 3, 4, 5, 6, 7, 8, 9")]
    pub event: ::core::option::Option<asset_event_envelope::Event>,
}
/// Nested message and enum types in `AssetEventEnvelope`.
pub mod asset_event_envelope {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "2")]
        AssetEnabled(super::AssetEnabled),
        #[prost(message, tag = "3")]
        AssetDisabled(super::AssetDisabled),
        #[prost(message, tag = "4")]
        BlockchainNetworkEnabled(super::BlockchainNetworkEnabled),
        #[prost(message, tag = "5")]
        BlockchainNetworkDisabled(super::BlockchainNetworkDisabled),
        #[prost(message, tag = "6")]
        AssetNetworkEnabled(super::AssetNetworkEnabled),
        #[prost(message, tag = "7")]
        AssetNetworkDisabled(super::AssetNetworkDisabled),
        #[prost(message, tag = "8")]
        FiatCurrencyEnabled(super::FiatCurrencyEnabled),
        #[prost(message, tag = "9")]
        FiatCurrencyDisabled(super::FiatCurrencyDisabled),
    }
}
impl ::prost::Name for AssetEventEnvelope {
    const NAME: &'static str = "AssetEventEnvelope";
    const PACKAGE: &'static str = "asset.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "asset.events.v1.AssetEventEnvelope".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/asset.events.v1.AssetEventEnvelope".into()
    }
}
