// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetAssetRequest {
    #[prost(enumeration = "super::super::shared::v1::AssetId", tag = "1")]
    pub asset_id: i32,
}
impl ::prost::Name for GetAssetRequest {
    const NAME: &'static str = "GetAssetRequest";
    const PACKAGE: &'static str = "asset.internal.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "asset.internal.v1.GetAssetRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/asset.internal.v1.GetAssetRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetAssetResponse {
    #[prost(message, optional, tag = "1")]
    pub asset: ::core::option::Option<super::super::shared::v1::Asset>,
}
impl ::prost::Name for GetAssetResponse {
    const NAME: &'static str = "GetAssetResponse";
    const PACKAGE: &'static str = "asset.internal.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "asset.internal.v1.GetAssetResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/asset.internal.v1.GetAssetResponse".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetBlockchainNetworkRequest {
    #[prost(enumeration = "super::super::shared::v1::NetworkId", tag = "1")]
    pub network_id: i32,
}
impl ::prost::Name for GetBlockchainNetworkRequest {
    const NAME: &'static str = "GetBlockchainNetworkRequest";
    const PACKAGE: &'static str = "asset.internal.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "asset.internal.v1.GetBlockchainNetworkRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/asset.internal.v1.GetBlockchainNetworkRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetBlockchainNetworkResponse {
    #[prost(message, optional, tag = "1")]
    pub blockchain_network: ::core::option::Option<
        super::super::shared::v1::BlockchainNetwork,
    >,
}
impl ::prost::Name for GetBlockchainNetworkResponse {
    const NAME: &'static str = "GetBlockchainNetworkResponse";
    const PACKAGE: &'static str = "asset.internal.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "asset.internal.v1.GetBlockchainNetworkResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/asset.internal.v1.GetBlockchainNetworkResponse".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetAssetNetworkRequest {
    #[prost(string, tag = "1")]
    pub asset_network_id: ::prost::alloc::string::String,
}
impl ::prost::Name for GetAssetNetworkRequest {
    const NAME: &'static str = "GetAssetNetworkRequest";
    const PACKAGE: &'static str = "asset.internal.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "asset.internal.v1.GetAssetNetworkRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/asset.internal.v1.GetAssetNetworkRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetAssetNetworkResponse {
    #[prost(message, optional, tag = "1")]
    pub asset_network: ::core::option::Option<super::super::shared::v1::AssetNetwork>,
    #[prost(message, optional, tag = "2")]
    pub configuration: ::core::option::Option<
        super::super::shared::v1::AssetNetworkConfiguration,
    >,
}
impl ::prost::Name for GetAssetNetworkResponse {
    const NAME: &'static str = "GetAssetNetworkResponse";
    const PACKAGE: &'static str = "asset.internal.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "asset.internal.v1.GetAssetNetworkResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/asset.internal.v1.GetAssetNetworkResponse".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListAssetNetworksRequest {
    #[prost(enumeration = "super::super::shared::v1::AssetId", optional, tag = "1")]
    pub asset_id: ::core::option::Option<i32>,
    #[prost(enumeration = "super::super::shared::v1::NetworkId", optional, tag = "2")]
    pub network_id: ::core::option::Option<i32>,
}
impl ::prost::Name for ListAssetNetworksRequest {
    const NAME: &'static str = "ListAssetNetworksRequest";
    const PACKAGE: &'static str = "asset.internal.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "asset.internal.v1.ListAssetNetworksRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/asset.internal.v1.ListAssetNetworksRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListAssetNetworksResponse {
    #[prost(message, repeated, tag = "1")]
    pub asset_networks: ::prost::alloc::vec::Vec<super::super::shared::v1::AssetNetwork>,
}
impl ::prost::Name for ListAssetNetworksResponse {
    const NAME: &'static str = "ListAssetNetworksResponse";
    const PACKAGE: &'static str = "asset.internal.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "asset.internal.v1.ListAssetNetworksResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/asset.internal.v1.ListAssetNetworksResponse".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResolveAssetNetworkRequest {
    #[prost(enumeration = "super::super::shared::v1::NetworkId", tag = "1")]
    pub network_id: i32,
    #[prost(string, tag = "2")]
    pub contract_address: ::prost::alloc::string::String,
}
impl ::prost::Name for ResolveAssetNetworkRequest {
    const NAME: &'static str = "ResolveAssetNetworkRequest";
    const PACKAGE: &'static str = "asset.internal.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "asset.internal.v1.ResolveAssetNetworkRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/asset.internal.v1.ResolveAssetNetworkRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResolveAssetNetworkResponse {
    #[prost(message, optional, tag = "1")]
    pub asset_network: ::core::option::Option<super::super::shared::v1::AssetNetwork>,
    #[prost(message, optional, tag = "2")]
    pub configuration: ::core::option::Option<
        super::super::shared::v1::AssetNetworkConfiguration,
    >,
}
impl ::prost::Name for ResolveAssetNetworkResponse {
    const NAME: &'static str = "ResolveAssetNetworkResponse";
    const PACKAGE: &'static str = "asset.internal.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "asset.internal.v1.ResolveAssetNetworkResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/asset.internal.v1.ResolveAssetNetworkResponse".into()
    }
}
/// Generated client implementations.
pub mod asset_internal_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct AssetInternalServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl AssetInternalServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> AssetInternalServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> AssetInternalServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            AssetInternalServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn get_asset(
            &mut self,
            request: impl tonic::IntoRequest<super::GetAssetRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetAssetResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/asset.internal.v1.AssetInternalService/GetAsset",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("asset.internal.v1.AssetInternalService", "GetAsset"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_blockchain_network(
            &mut self,
            request: impl tonic::IntoRequest<super::GetBlockchainNetworkRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetBlockchainNetworkResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/asset.internal.v1.AssetInternalService/GetBlockchainNetwork",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "asset.internal.v1.AssetInternalService",
                        "GetBlockchainNetwork",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_asset_network(
            &mut self,
            request: impl tonic::IntoRequest<super::GetAssetNetworkRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetAssetNetworkResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/asset.internal.v1.AssetInternalService/GetAssetNetwork",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "asset.internal.v1.AssetInternalService",
                        "GetAssetNetwork",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_asset_networks(
            &mut self,
            request: impl tonic::IntoRequest<super::ListAssetNetworksRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListAssetNetworksResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/asset.internal.v1.AssetInternalService/ListAssetNetworks",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "asset.internal.v1.AssetInternalService",
                        "ListAssetNetworks",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn resolve_asset_network(
            &mut self,
            request: impl tonic::IntoRequest<super::ResolveAssetNetworkRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ResolveAssetNetworkResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/asset.internal.v1.AssetInternalService/ResolveAssetNetwork",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "asset.internal.v1.AssetInternalService",
                        "ResolveAssetNetwork",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod asset_internal_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with AssetInternalServiceServer.
    #[async_trait]
    pub trait AssetInternalService: std::marker::Send + std::marker::Sync + 'static {
        async fn get_asset(
            &self,
            request: tonic::Request<super::GetAssetRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetAssetResponse>,
            tonic::Status,
        >;
        async fn get_blockchain_network(
            &self,
            request: tonic::Request<super::GetBlockchainNetworkRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetBlockchainNetworkResponse>,
            tonic::Status,
        >;
        async fn get_asset_network(
            &self,
            request: tonic::Request<super::GetAssetNetworkRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetAssetNetworkResponse>,
            tonic::Status,
        >;
        async fn list_asset_networks(
            &self,
            request: tonic::Request<super::ListAssetNetworksRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListAssetNetworksResponse>,
            tonic::Status,
        >;
        async fn resolve_asset_network(
            &self,
            request: tonic::Request<super::ResolveAssetNetworkRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ResolveAssetNetworkResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct AssetInternalServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> AssetInternalServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for AssetInternalServiceServer<T>
    where
        T: AssetInternalService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/asset.internal.v1.AssetInternalService/GetAsset" => {
                    #[allow(non_camel_case_types)]
                    struct GetAssetSvc<T: AssetInternalService>(pub Arc<T>);
                    impl<
                        T: AssetInternalService,
                    > tonic::server::UnaryService<super::GetAssetRequest>
                    for GetAssetSvc<T> {
                        type Response = super::GetAssetResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetAssetRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AssetInternalService>::get_asset(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetAssetSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/asset.internal.v1.AssetInternalService/GetBlockchainNetwork" => {
                    #[allow(non_camel_case_types)]
                    struct GetBlockchainNetworkSvc<T: AssetInternalService>(pub Arc<T>);
                    impl<
                        T: AssetInternalService,
                    > tonic::server::UnaryService<super::GetBlockchainNetworkRequest>
                    for GetBlockchainNetworkSvc<T> {
                        type Response = super::GetBlockchainNetworkResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetBlockchainNetworkRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AssetInternalService>::get_blockchain_network(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetBlockchainNetworkSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/asset.internal.v1.AssetInternalService/GetAssetNetwork" => {
                    #[allow(non_camel_case_types)]
                    struct GetAssetNetworkSvc<T: AssetInternalService>(pub Arc<T>);
                    impl<
                        T: AssetInternalService,
                    > tonic::server::UnaryService<super::GetAssetNetworkRequest>
                    for GetAssetNetworkSvc<T> {
                        type Response = super::GetAssetNetworkResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetAssetNetworkRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AssetInternalService>::get_asset_network(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetAssetNetworkSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/asset.internal.v1.AssetInternalService/ListAssetNetworks" => {
                    #[allow(non_camel_case_types)]
                    struct ListAssetNetworksSvc<T: AssetInternalService>(pub Arc<T>);
                    impl<
                        T: AssetInternalService,
                    > tonic::server::UnaryService<super::ListAssetNetworksRequest>
                    for ListAssetNetworksSvc<T> {
                        type Response = super::ListAssetNetworksResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListAssetNetworksRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AssetInternalService>::list_asset_networks(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListAssetNetworksSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/asset.internal.v1.AssetInternalService/ResolveAssetNetwork" => {
                    #[allow(non_camel_case_types)]
                    struct ResolveAssetNetworkSvc<T: AssetInternalService>(pub Arc<T>);
                    impl<
                        T: AssetInternalService,
                    > tonic::server::UnaryService<super::ResolveAssetNetworkRequest>
                    for ResolveAssetNetworkSvc<T> {
                        type Response = super::ResolveAssetNetworkResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ResolveAssetNetworkRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AssetInternalService>::resolve_asset_network(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ResolveAssetNetworkSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for AssetInternalServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "asset.internal.v1.AssetInternalService";
    impl<T> tonic::server::NamedService for AssetInternalServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
