// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FiatCurrencyItem {
    #[prost(
        enumeration = "super::super::super::shared::enums::v1::FiatCurrency",
        tag = "1"
    )]
    pub id: i32,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub logo: ::prost::alloc::string::String,
    #[prost(uint32, tag = "5")]
    pub decimals: u32,
    #[prost(enumeration = "CurrencyStatus", tag = "6")]
    pub status: i32,
}
impl ::prost::Name for FiatCurrencyItem {
    const NAME: &'static str = "FiatCurrencyItem";
    const PACKAGE: &'static str = "billing.currency.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.currency.v1.FiatCurrencyItem".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.currency.v1.FiatCurrencyItem".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PricingCurrencyItem {
    #[prost(
        enumeration = "super::super::super::shared::enums::v1::PricingCurrency",
        tag = "1"
    )]
    pub id: i32,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub logo: ::prost::alloc::string::String,
    #[prost(uint32, tag = "5")]
    pub decimals: u32,
    #[prost(enumeration = "CurrencyStatus", tag = "6")]
    pub status: i32,
    #[prost(enumeration = "CurrencyType", tag = "7")]
    pub r#type: i32,
}
impl ::prost::Name for PricingCurrencyItem {
    const NAME: &'static str = "PricingCurrencyItem";
    const PACKAGE: &'static str = "billing.currency.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.currency.v1.PricingCurrencyItem".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.currency.v1.PricingCurrencyItem".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PaymentCurrencyNetwork {
    #[prost(
        enumeration = "super::super::super::shared::enums::v1::NetworkId",
        tag = "1"
    )]
    pub network_id: i32,
    #[prost(enumeration = "super::super::super::shared::enums::v1::Chain", tag = "2")]
    pub chain: i32,
    #[prost(
        enumeration = "super::super::super::shared::enums::v1::CryptoStandard",
        tag = "3"
    )]
    pub standard: i32,
    #[prost(bool, tag = "4")]
    pub is_native: bool,
    #[prost(string, tag = "5")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub logo: ::prost::alloc::string::String,
}
impl ::prost::Name for PaymentCurrencyNetwork {
    const NAME: &'static str = "PaymentCurrencyNetwork";
    const PACKAGE: &'static str = "billing.currency.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.currency.v1.PaymentCurrencyNetwork".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.currency.v1.PaymentCurrencyNetwork".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PaymentCurrencyItem {
    #[prost(
        enumeration = "super::super::super::shared::enums::v1::PaymentCurrency",
        tag = "1"
    )]
    pub id: i32,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub logo: ::prost::alloc::string::String,
    #[prost(uint32, tag = "5")]
    pub decimals: u32,
    #[prost(enumeration = "CurrencyStatus", tag = "6")]
    pub status: i32,
    #[prost(message, repeated, tag = "7")]
    pub networks: ::prost::alloc::vec::Vec<PaymentCurrencyNetwork>,
}
impl ::prost::Name for PaymentCurrencyItem {
    const NAME: &'static str = "PaymentCurrencyItem";
    const PACKAGE: &'static str = "billing.currency.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.currency.v1.PaymentCurrencyItem".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.currency.v1.PaymentCurrencyItem".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChainItem {
    #[prost(enumeration = "super::super::super::shared::enums::v1::Chain", tag = "1")]
    pub id: i32,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub logo: ::prost::alloc::string::String,
    #[prost(
        enumeration = "super::super::super::shared::enums::v1::PaymentCurrency",
        repeated,
        tag = "4"
    )]
    pub currencies: ::prost::alloc::vec::Vec<i32>,
}
impl ::prost::Name for ChainItem {
    const NAME: &'static str = "ChainItem";
    const PACKAGE: &'static str = "billing.currency.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.currency.v1.ChainItem".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.currency.v1.ChainItem".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NetworkItem {
    #[prost(
        enumeration = "super::super::super::shared::enums::v1::NetworkId",
        tag = "1"
    )]
    pub id: i32,
    #[prost(enumeration = "super::super::super::shared::enums::v1::Chain", tag = "2")]
    pub chain: i32,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub logo: ::prost::alloc::string::String,
    #[prost(bool, tag = "5")]
    pub is_testnet: bool,
    #[prost(
        enumeration = "super::super::super::shared::enums::v1::PaymentCurrency",
        repeated,
        tag = "6"
    )]
    pub currencies: ::prost::alloc::vec::Vec<i32>,
}
impl ::prost::Name for NetworkItem {
    const NAME: &'static str = "NetworkItem";
    const PACKAGE: &'static str = "billing.currency.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.currency.v1.NetworkItem".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.currency.v1.NetworkItem".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListCurrenciesRequest {}
impl ::prost::Name for ListCurrenciesRequest {
    const NAME: &'static str = "ListCurrenciesRequest";
    const PACKAGE: &'static str = "billing.currency.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.currency.v1.ListCurrenciesRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.currency.v1.ListCurrenciesRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListCurrenciesResponse {
    #[prost(message, repeated, tag = "1")]
    pub fiat_currencies: ::prost::alloc::vec::Vec<FiatCurrencyItem>,
    #[prost(message, repeated, tag = "3")]
    pub pricing_currencies: ::prost::alloc::vec::Vec<PricingCurrencyItem>,
    #[prost(message, repeated, tag = "4")]
    pub payment_currencies: ::prost::alloc::vec::Vec<PaymentCurrencyItem>,
    #[prost(message, repeated, tag = "5")]
    pub chains: ::prost::alloc::vec::Vec<ChainItem>,
    #[prost(message, repeated, tag = "6")]
    pub networks: ::prost::alloc::vec::Vec<NetworkItem>,
}
impl ::prost::Name for ListCurrenciesResponse {
    const NAME: &'static str = "ListCurrenciesResponse";
    const PACKAGE: &'static str = "billing.currency.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.currency.v1.ListCurrenciesResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.currency.v1.ListCurrenciesResponse".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CurrencyRate {
    #[prost(
        enumeration = "super::super::super::shared::enums::v1::PaymentCurrency",
        tag = "1"
    )]
    pub base_currency: i32,
    #[prost(string, tag = "2")]
    pub quote_currency: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub rate: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "4")]
    pub updated_at: ::core::option::Option<::prost_wkt_types::Timestamp>,
}
impl ::prost::Name for CurrencyRate {
    const NAME: &'static str = "CurrencyRate";
    const PACKAGE: &'static str = "billing.currency.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.currency.v1.CurrencyRate".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.currency.v1.CurrencyRate".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListCurrencyRatesRequest {}
impl ::prost::Name for ListCurrencyRatesRequest {
    const NAME: &'static str = "ListCurrencyRatesRequest";
    const PACKAGE: &'static str = "billing.currency.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.currency.v1.ListCurrencyRatesRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.currency.v1.ListCurrencyRatesRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListCurrencyRatesResponse {
    #[prost(message, repeated, tag = "1")]
    pub rates: ::prost::alloc::vec::Vec<CurrencyRate>,
}
impl ::prost::Name for ListCurrencyRatesResponse {
    const NAME: &'static str = "ListCurrencyRatesResponse";
    const PACKAGE: &'static str = "billing.currency.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.currency.v1.ListCurrencyRatesResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.currency.v1.ListCurrencyRatesResponse".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CurrencyStatus {
    Unspecified = 0,
    Enabled = 1,
    Disabled = 2,
}
impl CurrencyStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CURRENCY_STATUS_UNSPECIFIED",
            Self::Enabled => "CURRENCY_STATUS_ENABLED",
            Self::Disabled => "CURRENCY_STATUS_DISABLED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CURRENCY_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "CURRENCY_STATUS_ENABLED" => Some(Self::Enabled),
            "CURRENCY_STATUS_DISABLED" => Some(Self::Disabled),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CurrencyType {
    Unspecified = 0,
    Fiat = 1,
    Crypto = 2,
}
impl CurrencyType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CURRENCY_TYPE_UNSPECIFIED",
            Self::Fiat => "CURRENCY_TYPE_FIAT",
            Self::Crypto => "CURRENCY_TYPE_CRYPTO",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CURRENCY_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "CURRENCY_TYPE_FIAT" => Some(Self::Fiat),
            "CURRENCY_TYPE_CRYPTO" => Some(Self::Crypto),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod currency_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct CurrencyServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl CurrencyServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> CurrencyServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> CurrencyServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            CurrencyServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn list_currencies(
            &mut self,
            request: impl tonic::IntoRequest<super::ListCurrenciesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListCurrenciesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/billing.currency.v1.CurrencyService/ListCurrencies",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "billing.currency.v1.CurrencyService",
                        "ListCurrencies",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_currency_rates(
            &mut self,
            request: impl tonic::IntoRequest<super::ListCurrencyRatesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListCurrencyRatesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/billing.currency.v1.CurrencyService/ListCurrencyRates",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "billing.currency.v1.CurrencyService",
                        "ListCurrencyRates",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod currency_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with CurrencyServiceServer.
    #[async_trait]
    pub trait CurrencyService: std::marker::Send + std::marker::Sync + 'static {
        async fn list_currencies(
            &self,
            request: tonic::Request<super::ListCurrenciesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListCurrenciesResponse>,
            tonic::Status,
        >;
        async fn list_currency_rates(
            &self,
            request: tonic::Request<super::ListCurrencyRatesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListCurrencyRatesResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct CurrencyServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> CurrencyServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for CurrencyServiceServer<T>
    where
        T: CurrencyService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/billing.currency.v1.CurrencyService/ListCurrencies" => {
                    #[allow(non_camel_case_types)]
                    struct ListCurrenciesSvc<T: CurrencyService>(pub Arc<T>);
                    impl<
                        T: CurrencyService,
                    > tonic::server::UnaryService<super::ListCurrenciesRequest>
                    for ListCurrenciesSvc<T> {
                        type Response = super::ListCurrenciesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListCurrenciesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CurrencyService>::list_currencies(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListCurrenciesSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/billing.currency.v1.CurrencyService/ListCurrencyRates" => {
                    #[allow(non_camel_case_types)]
                    struct ListCurrencyRatesSvc<T: CurrencyService>(pub Arc<T>);
                    impl<
                        T: CurrencyService,
                    > tonic::server::UnaryService<super::ListCurrencyRatesRequest>
                    for ListCurrencyRatesSvc<T> {
                        type Response = super::ListCurrencyRatesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListCurrencyRatesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as CurrencyService>::list_currency_rates(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListCurrencyRatesSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for CurrencyServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "billing.currency.v1.CurrencyService";
    impl<T> tonic::server::NamedService for CurrencyServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
