// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InvoiceAmounts {
    #[prost(message, optional, tag = "1")]
    pub pricing: ::core::option::Option<
        super::super::super::super::shared::types::v1::Money,
    >,
    #[prost(message, optional, tag = "2")]
    pub payable: ::core::option::Option<
        super::super::super::super::shared::types::v1::Money,
    >,
    #[prost(message, optional, tag = "3")]
    pub paid: ::core::option::Option<
        super::super::super::super::shared::types::v1::Money,
    >,
    #[prost(message, optional, tag = "4")]
    pub due: ::core::option::Option<
        super::super::super::super::shared::types::v1::Money,
    >,
}
impl ::prost::Name for InvoiceAmounts {
    const NAME: &'static str = "InvoiceAmounts";
    const PACKAGE: &'static str = "billing.invoice.shared.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.invoice.shared.v1.InvoiceAmounts".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.invoice.shared.v1.InvoiceAmounts".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PaymentIntent {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub external_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub redirect_url: ::core::option::Option<::prost::alloc::string::String>,
}
impl ::prost::Name for PaymentIntent {
    const NAME: &'static str = "PaymentIntent";
    const PACKAGE: &'static str = "billing.invoice.shared.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.invoice.shared.v1.PaymentIntent".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.invoice.shared.v1.PaymentIntent".into()
    }
}
