// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Invoice {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub store_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub address: ::core::option::Option<
        super::super::super::super::shared::types::v1::CryptoAddress,
    >,
    #[prost(message, optional, tag = "4")]
    pub amounts: ::core::option::Option<super::super::super::shared::v1::InvoiceAmounts>,
    #[prost(message, optional, tag = "5")]
    pub exchange_rate: ::core::option::Option<
        super::super::super::shared::v1::ExchangeRate,
    >,
    #[prost(enumeration = "super::super::super::shared::v1::InvoiceStatus", tag = "6")]
    pub status: i32,
    #[prost(
        enumeration = "super::super::super::shared::v1::InvoiceAdditionalStatus",
        tag = "7"
    )]
    pub additional_status: i32,
    #[prost(message, optional, tag = "8")]
    pub created_at: ::core::option::Option<::pbjson_types::Timestamp>,
    #[prost(message, optional, tag = "9")]
    pub expires_at: ::core::option::Option<::pbjson_types::Timestamp>,
    #[prost(message, optional, tag = "10")]
    pub payment_intent: ::core::option::Option<
        super::super::super::shared::v1::InvoicePaymentIntent,
    >,
    #[prost(message, optional, tag = "11")]
    pub confirmations: ::core::option::Option<
        super::super::super::shared::v1::ConfirmationDetails,
    >,
    #[prost(message, repeated, tag = "12")]
    pub transactions: ::prost::alloc::vec::Vec<
        super::super::super::shared::v1::InvoiceTransaction,
    >,
    #[prost(string, tag = "13")]
    pub checkout_url: ::prost::alloc::string::String,
    #[prost(
        enumeration = "super::super::super::super::shared::enums::v1::NetworkId",
        tag = "14"
    )]
    pub network_id: i32,
    #[prost(message, optional, tag = "15")]
    pub store: ::core::option::Option<super::super::super::shared::v1::StoreBranding>,
    #[prost(
        enumeration = "super::super::super::super::shared::enums::v1::PaymentCurrency",
        tag = "16"
    )]
    pub payment_currency: i32,
}
impl ::prost::Name for Invoice {
    const NAME: &'static str = "Invoice";
    const PACKAGE: &'static str = "billing.invoice.public.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.invoice.public.v1.Invoice".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.invoice.public.v1.Invoice".into()
    }
}
/// ======= GetInvoice =======
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetInvoiceRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
impl ::prost::Name for GetInvoiceRequest {
    const NAME: &'static str = "GetInvoiceRequest";
    const PACKAGE: &'static str = "billing.invoice.public.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.invoice.public.v1.GetInvoiceRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.invoice.public.v1.GetInvoiceRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetInvoiceResponse {
    #[prost(message, optional, tag = "1")]
    pub invoice: ::core::option::Option<Invoice>,
}
impl ::prost::Name for GetInvoiceResponse {
    const NAME: &'static str = "GetInvoiceResponse";
    const PACKAGE: &'static str = "billing.invoice.public.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.invoice.public.v1.GetInvoiceResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.invoice.public.v1.GetInvoiceResponse".into()
    }
}
/// ======= CreateInvoice =======
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateInvoiceRequest {
    #[prost(string, tag = "1")]
    pub pricing_amount: ::prost::alloc::string::String,
    #[prost(
        enumeration = "super::super::super::super::shared::enums::v1::PricingCurrency",
        tag = "2"
    )]
    pub pricing_currency: i32,
    #[prost(
        enumeration = "super::super::super::super::shared::enums::v1::PaymentCurrency",
        tag = "3"
    )]
    pub payment_currency: i32,
    #[prost(string, optional, tag = "4")]
    pub redirect_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub external_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(
        enumeration = "super::super::super::super::shared::enums::v1::NetworkId",
        tag = "6"
    )]
    pub network_id: i32,
    #[prost(uint32, optional, tag = "7")]
    pub expiration_minutes: ::core::option::Option<u32>,
}
impl ::prost::Name for CreateInvoiceRequest {
    const NAME: &'static str = "CreateInvoiceRequest";
    const PACKAGE: &'static str = "billing.invoice.public.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.invoice.public.v1.CreateInvoiceRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.invoice.public.v1.CreateInvoiceRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateInvoiceResponse {
    #[prost(message, optional, tag = "1")]
    pub invoice: ::core::option::Option<Invoice>,
    #[prost(string, tag = "2")]
    pub checkout_url: ::prost::alloc::string::String,
}
impl ::prost::Name for CreateInvoiceResponse {
    const NAME: &'static str = "CreateInvoiceResponse";
    const PACKAGE: &'static str = "billing.invoice.public.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.invoice.public.v1.CreateInvoiceResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.invoice.public.v1.CreateInvoiceResponse".into()
    }
}
/// ======= CreateInvoiceForPaymentIntent =======
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateInvoiceForPaymentIntentRequest {
    #[prost(string, tag = "1")]
    pub payment_intent_id: ::prost::alloc::string::String,
    #[prost(
        enumeration = "super::super::super::super::shared::enums::v1::PaymentCurrency",
        tag = "2"
    )]
    pub payment_currency: i32,
    #[prost(
        enumeration = "super::super::super::super::shared::enums::v1::NetworkId",
        tag = "3"
    )]
    pub network_id: i32,
    #[prost(uint32, optional, tag = "4")]
    pub expiration_minutes: ::core::option::Option<u32>,
}
impl ::prost::Name for CreateInvoiceForPaymentIntentRequest {
    const NAME: &'static str = "CreateInvoiceForPaymentIntentRequest";
    const PACKAGE: &'static str = "billing.invoice.public.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.invoice.public.v1.CreateInvoiceForPaymentIntentRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.invoice.public.v1.CreateInvoiceForPaymentIntentRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateInvoiceForPaymentIntentResponse {
    #[prost(message, optional, tag = "1")]
    pub invoice: ::core::option::Option<Invoice>,
}
impl ::prost::Name for CreateInvoiceForPaymentIntentResponse {
    const NAME: &'static str = "CreateInvoiceForPaymentIntentResponse";
    const PACKAGE: &'static str = "billing.invoice.public.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.invoice.public.v1.CreateInvoiceForPaymentIntentResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.invoice.public.v1.CreateInvoiceForPaymentIntentResponse".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubscribeInvoiceRequest {
    #[prost(string, tag = "1")]
    pub invoice_id: ::prost::alloc::string::String,
}
impl ::prost::Name for SubscribeInvoiceRequest {
    const NAME: &'static str = "SubscribeInvoiceRequest";
    const PACKAGE: &'static str = "billing.invoice.public.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.invoice.public.v1.SubscribeInvoiceRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.invoice.public.v1.SubscribeInvoiceRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubscribeInvoiceResponse {
    #[prost(enumeration = "super::super::super::shared::v1::InvoiceStatus", tag = "1")]
    pub status: i32,
    #[prost(
        enumeration = "super::super::super::shared::v1::InvoiceAdditionalStatus",
        tag = "2"
    )]
    pub additional_status: i32,
    #[prost(message, optional, tag = "3")]
    pub paid_amount: ::core::option::Option<
        super::super::super::super::shared::types::v1::Money,
    >,
    #[prost(message, optional, tag = "4")]
    pub due_amount: ::core::option::Option<
        super::super::super::super::shared::types::v1::Money,
    >,
    #[prost(message, optional, tag = "5")]
    pub timestamp: ::core::option::Option<::pbjson_types::Timestamp>,
}
impl ::prost::Name for SubscribeInvoiceResponse {
    const NAME: &'static str = "SubscribeInvoiceResponse";
    const PACKAGE: &'static str = "billing.invoice.public.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.invoice.public.v1.SubscribeInvoiceResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.invoice.public.v1.SubscribeInvoiceResponse".into()
    }
}
/// Generated client implementations.
pub mod invoice_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct InvoiceServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl InvoiceServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> InvoiceServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InvoiceServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            InvoiceServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// / Get a specific invoice by ID
        pub async fn get_invoice(
            &mut self,
            request: impl tonic::IntoRequest<super::GetInvoiceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetInvoiceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/billing.invoice.public.v1.InvoiceService/GetInvoice",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "billing.invoice.public.v1.InvoiceService",
                        "GetInvoice",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// / Create a new invoice
        pub async fn create_invoice(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateInvoiceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateInvoiceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/billing.invoice.public.v1.InvoiceService/CreateInvoice",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "billing.invoice.public.v1.InvoiceService",
                        "CreateInvoice",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// / Create a new invoice for payment
        pub async fn create_invoice_for_payment_intent(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateInvoiceForPaymentIntentRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateInvoiceForPaymentIntentResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/billing.invoice.public.v1.InvoiceService/CreateInvoiceForPaymentIntent",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "billing.invoice.public.v1.InvoiceService",
                        "CreateInvoiceForPaymentIntent",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// / ✅ Stream invoice lifecycle events (paid, expired, partial, etc.)
        pub async fn subscribe_invoice(
            &mut self,
            request: impl tonic::IntoRequest<super::SubscribeInvoiceRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::SubscribeInvoiceResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/billing.invoice.public.v1.InvoiceService/SubscribeInvoice",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "billing.invoice.public.v1.InvoiceService",
                        "SubscribeInvoice",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod invoice_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with InvoiceServiceServer.
    #[async_trait]
    pub trait InvoiceService: std::marker::Send + std::marker::Sync + 'static {
        /// / Get a specific invoice by ID
        async fn get_invoice(
            &self,
            request: tonic::Request<super::GetInvoiceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetInvoiceResponse>,
            tonic::Status,
        >;
        /// / Create a new invoice
        async fn create_invoice(
            &self,
            request: tonic::Request<super::CreateInvoiceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateInvoiceResponse>,
            tonic::Status,
        >;
        /// / Create a new invoice for payment
        async fn create_invoice_for_payment_intent(
            &self,
            request: tonic::Request<super::CreateInvoiceForPaymentIntentRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateInvoiceForPaymentIntentResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the SubscribeInvoice method.
        type SubscribeInvoiceStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<
                    super::SubscribeInvoiceResponse,
                    tonic::Status,
                >,
            >
            + std::marker::Send
            + 'static;
        /// / ✅ Stream invoice lifecycle events (paid, expired, partial, etc.)
        async fn subscribe_invoice(
            &self,
            request: tonic::Request<super::SubscribeInvoiceRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::SubscribeInvoiceStream>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct InvoiceServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> InvoiceServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for InvoiceServiceServer<T>
    where
        T: InvoiceService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/billing.invoice.public.v1.InvoiceService/GetInvoice" => {
                    #[allow(non_camel_case_types)]
                    struct GetInvoiceSvc<T: InvoiceService>(pub Arc<T>);
                    impl<
                        T: InvoiceService,
                    > tonic::server::UnaryService<super::GetInvoiceRequest>
                    for GetInvoiceSvc<T> {
                        type Response = super::GetInvoiceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetInvoiceRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as InvoiceService>::get_invoice(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetInvoiceSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/billing.invoice.public.v1.InvoiceService/CreateInvoice" => {
                    #[allow(non_camel_case_types)]
                    struct CreateInvoiceSvc<T: InvoiceService>(pub Arc<T>);
                    impl<
                        T: InvoiceService,
                    > tonic::server::UnaryService<super::CreateInvoiceRequest>
                    for CreateInvoiceSvc<T> {
                        type Response = super::CreateInvoiceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateInvoiceRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as InvoiceService>::create_invoice(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateInvoiceSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/billing.invoice.public.v1.InvoiceService/CreateInvoiceForPaymentIntent" => {
                    #[allow(non_camel_case_types)]
                    struct CreateInvoiceForPaymentIntentSvc<T: InvoiceService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: InvoiceService,
                    > tonic::server::UnaryService<
                        super::CreateInvoiceForPaymentIntentRequest,
                    > for CreateInvoiceForPaymentIntentSvc<T> {
                        type Response = super::CreateInvoiceForPaymentIntentResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::CreateInvoiceForPaymentIntentRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as InvoiceService>::create_invoice_for_payment_intent(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateInvoiceForPaymentIntentSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/billing.invoice.public.v1.InvoiceService/SubscribeInvoice" => {
                    #[allow(non_camel_case_types)]
                    struct SubscribeInvoiceSvc<T: InvoiceService>(pub Arc<T>);
                    impl<
                        T: InvoiceService,
                    > tonic::server::ServerStreamingService<
                        super::SubscribeInvoiceRequest,
                    > for SubscribeInvoiceSvc<T> {
                        type Response = super::SubscribeInvoiceResponse;
                        type ResponseStream = T::SubscribeInvoiceStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SubscribeInvoiceRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as InvoiceService>::subscribe_invoice(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SubscribeInvoiceSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for InvoiceServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "billing.invoice.public.v1.InvoiceService";
    impl<T> tonic::server::NamedService for InvoiceServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
