// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PricingPlanCreated {
    #[prost(string, tag = "1")]
    pub pricing_plan_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "4")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, tag = "5")]
    pub transaction_fee_bps: i32,
    #[prost(message, optional, tag = "6")]
    pub transaction_fixed_fee: ::core::option::Option<
        super::super::super::super::shared::types::v1::EventMoney,
    >,
    #[prost(message, optional, tag = "7")]
    pub monthly_price: ::core::option::Option<
        super::super::super::super::shared::types::v1::EventMoney,
    >,
    #[prost(string, tag = "8")]
    pub monthly_volume_threshold: ::prost::alloc::string::String,
    #[prost(uint32, tag = "9")]
    pub free_trial_days: u32,
    #[prost(string, optional, tag = "10")]
    pub tag: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "11")]
    pub features: ::prost::alloc::vec::Vec<super::super::shared::v1::PricingPlanFeature>,
    #[prost(
        enumeration = "super::super::shared::v1::PricingPlanPurchaseMode",
        tag = "12"
    )]
    pub purchase_mode: i32,
    #[prost(int32, optional, tag = "13")]
    pub tier: ::core::option::Option<i32>,
    #[prost(bool, tag = "14")]
    pub is_default: bool,
    #[prost(message, optional, tag = "15")]
    pub created_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
impl ::prost::Name for PricingPlanCreated {
    const NAME: &'static str = "PricingPlanCreated";
    const PACKAGE: &'static str = "billing.pricing_plan.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.pricing_plan.events.v1.PricingPlanCreated".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.pricing_plan.events.v1.PricingPlanCreated".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PricingPlanUpdated {
    #[prost(string, tag = "1")]
    pub pricing_plan_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub updated_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
impl ::prost::Name for PricingPlanUpdated {
    const NAME: &'static str = "PricingPlanUpdated";
    const PACKAGE: &'static str = "billing.pricing_plan.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.pricing_plan.events.v1.PricingPlanUpdated".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.pricing_plan.events.v1.PricingPlanUpdated".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PricingPlanActivated {
    #[prost(string, tag = "1")]
    pub pricing_plan_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub activated_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
impl ::prost::Name for PricingPlanActivated {
    const NAME: &'static str = "PricingPlanActivated";
    const PACKAGE: &'static str = "billing.pricing_plan.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.pricing_plan.events.v1.PricingPlanActivated".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.pricing_plan.events.v1.PricingPlanActivated".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PricingPlanDeactivated {
    #[prost(string, tag = "1")]
    pub pricing_plan_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub deactivated_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
impl ::prost::Name for PricingPlanDeactivated {
    const NAME: &'static str = "PricingPlanDeactivated";
    const PACKAGE: &'static str = "billing.pricing_plan.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.pricing_plan.events.v1.PricingPlanDeactivated".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.pricing_plan.events.v1.PricingPlanDeactivated".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PricingPlanDeleted {
    #[prost(string, tag = "1")]
    pub pricing_plan_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub deleted_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
impl ::prost::Name for PricingPlanDeleted {
    const NAME: &'static str = "PricingPlanDeleted";
    const PACKAGE: &'static str = "billing.pricing_plan.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.pricing_plan.events.v1.PricingPlanDeleted".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.pricing_plan.events.v1.PricingPlanDeleted".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PricingPlanEventEnvelope {
    #[prost(message, optional, tag = "1")]
    pub meta: ::core::option::Option<
        super::super::super::super::shared::events::v1::EventMetadata,
    >,
    #[prost(oneof = "pricing_plan_event_envelope::Event", tags = "2, 3, 4, 5, 6")]
    pub event: ::core::option::Option<pricing_plan_event_envelope::Event>,
}
/// Nested message and enum types in `PricingPlanEventEnvelope`.
pub mod pricing_plan_event_envelope {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "2")]
        Created(super::PricingPlanCreated),
        #[prost(message, tag = "3")]
        Updated(super::PricingPlanUpdated),
        #[prost(message, tag = "4")]
        Activated(super::PricingPlanActivated),
        #[prost(message, tag = "5")]
        Deactivated(super::PricingPlanDeactivated),
        #[prost(message, tag = "6")]
        Deleted(super::PricingPlanDeleted),
    }
}
impl ::prost::Name for PricingPlanEventEnvelope {
    const NAME: &'static str = "PricingPlanEventEnvelope";
    const PACKAGE: &'static str = "billing.pricing_plan.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.pricing_plan.events.v1.PricingPlanEventEnvelope".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.pricing_plan.events.v1.PricingPlanEventEnvelope".into()
    }
}
