// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Invoice {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub address: ::core::option::Option<
        super::super::super::super::shared::types::v1::CryptoAddress,
    >,
    #[prost(message, optional, tag = "3")]
    pub amounts: ::core::option::Option<super::super::shared::v1::InvoiceAmounts>,
    #[prost(message, optional, tag = "4")]
    pub exchange_rate: ::core::option::Option<
        super::super::super::shared::v1::ExchangeRate,
    >,
    #[prost(enumeration = "super::super::super::shared::v1::InvoiceStatus", tag = "5")]
    pub status: i32,
    #[prost(
        enumeration = "super::super::super::shared::v1::InvoiceAdditionalStatus",
        tag = "6"
    )]
    pub additional_status: i32,
    #[prost(message, optional, tag = "7")]
    pub created_at: ::core::option::Option<::prost_wkt_types::Timestamp>,
    #[prost(message, optional, tag = "8")]
    pub updated_at: ::core::option::Option<::prost_wkt_types::Timestamp>,
    #[prost(message, optional, tag = "9")]
    pub expires_at: ::core::option::Option<::prost_wkt_types::Timestamp>,
    #[prost(message, optional, tag = "10")]
    pub payment_intent: ::core::option::Option<super::super::shared::v1::PaymentIntent>,
    #[prost(message, repeated, tag = "11")]
    pub transactions: ::prost::alloc::vec::Vec<
        super::super::super::shared::v1::InvoiceTransaction,
    >,
    #[prost(string, tag = "12")]
    pub checkout_url: ::prost::alloc::string::String,
    #[prost(
        enumeration = "super::super::super::super::shared::enums::v1::NetworkId",
        tag = "13"
    )]
    pub network_id: i32,
}
impl ::prost::Name for Invoice {
    const NAME: &'static str = "Invoice";
    const PACKAGE: &'static str = "billing.invoice.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.invoice.merchant.v1.Invoice".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.invoice.merchant.v1.Invoice".into()
    }
}
/// ======= GetInvoice =======
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetInvoiceRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
impl ::prost::Name for GetInvoiceRequest {
    const NAME: &'static str = "GetInvoiceRequest";
    const PACKAGE: &'static str = "billing.invoice.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.invoice.merchant.v1.GetInvoiceRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.invoice.merchant.v1.GetInvoiceRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetInvoiceResponse {
    #[prost(message, optional, tag = "1")]
    pub invoice: ::core::option::Option<Invoice>,
}
impl ::prost::Name for GetInvoiceResponse {
    const NAME: &'static str = "GetInvoiceResponse";
    const PACKAGE: &'static str = "billing.invoice.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.invoice.merchant.v1.GetInvoiceResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.invoice.merchant.v1.GetInvoiceResponse".into()
    }
}
/// ======= ListInvoices =======
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListInvoicesRequest {
    #[prost(string, optional, tag = "1")]
    pub address: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(
        enumeration = "super::super::super::super::shared::enums::v1::PaymentCurrency",
        repeated,
        tag = "2"
    )]
    pub payment_currency: ::prost::alloc::vec::Vec<i32>,
    #[prost(
        enumeration = "super::super::super::shared::v1::InvoiceStatus",
        repeated,
        tag = "3"
    )]
    pub status: ::prost::alloc::vec::Vec<i32>,
    #[prost(
        enumeration = "super::super::super::shared::v1::InvoiceAdditionalStatus",
        repeated,
        tag = "4"
    )]
    pub additional_status: ::prost::alloc::vec::Vec<i32>,
    #[prost(
        enumeration = "super::super::super::super::shared::enums::v1::NetworkId",
        repeated,
        tag = "5"
    )]
    pub network_id: ::prost::alloc::vec::Vec<i32>,
    #[prost(string, optional, tag = "6")]
    pub payment_intent_id: ::core::option::Option<::prost::alloc::string::String>,
}
impl ::prost::Name for ListInvoicesRequest {
    const NAME: &'static str = "ListInvoicesRequest";
    const PACKAGE: &'static str = "billing.invoice.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.invoice.merchant.v1.ListInvoicesRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.invoice.merchant.v1.ListInvoicesRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListInvoicesResponse {
    #[prost(message, repeated, tag = "1")]
    pub invoices: ::prost::alloc::vec::Vec<Invoice>,
}
impl ::prost::Name for ListInvoicesResponse {
    const NAME: &'static str = "ListInvoicesResponse";
    const PACKAGE: &'static str = "billing.invoice.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.invoice.merchant.v1.ListInvoicesResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.invoice.merchant.v1.ListInvoicesResponse".into()
    }
}
/// Generated client implementations.
pub mod merchant_invoice_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct MerchantInvoiceServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl MerchantInvoiceServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> MerchantInvoiceServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> MerchantInvoiceServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            MerchantInvoiceServiceClient::new(
                InterceptedService::new(inner, interceptor),
            )
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Get a specific invoice by ID
        pub async fn get_invoice(
            &mut self,
            request: impl tonic::IntoRequest<super::GetInvoiceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetInvoiceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/billing.invoice.merchant.v1.MerchantInvoiceService/GetInvoice",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "billing.invoice.merchant.v1.MerchantInvoiceService",
                        "GetInvoice",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// List all invoices
        pub async fn list_invoices(
            &mut self,
            request: impl tonic::IntoRequest<super::ListInvoicesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListInvoicesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/billing.invoice.merchant.v1.MerchantInvoiceService/ListInvoices",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "billing.invoice.merchant.v1.MerchantInvoiceService",
                        "ListInvoices",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod merchant_invoice_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with MerchantInvoiceServiceServer.
    #[async_trait]
    pub trait MerchantInvoiceService: std::marker::Send + std::marker::Sync + 'static {
        /// Get a specific invoice by ID
        async fn get_invoice(
            &self,
            request: tonic::Request<super::GetInvoiceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetInvoiceResponse>,
            tonic::Status,
        >;
        /// List all invoices
        async fn list_invoices(
            &self,
            request: tonic::Request<super::ListInvoicesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListInvoicesResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct MerchantInvoiceServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> MerchantInvoiceServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for MerchantInvoiceServiceServer<T>
    where
        T: MerchantInvoiceService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/billing.invoice.merchant.v1.MerchantInvoiceService/GetInvoice" => {
                    #[allow(non_camel_case_types)]
                    struct GetInvoiceSvc<T: MerchantInvoiceService>(pub Arc<T>);
                    impl<
                        T: MerchantInvoiceService,
                    > tonic::server::UnaryService<super::GetInvoiceRequest>
                    for GetInvoiceSvc<T> {
                        type Response = super::GetInvoiceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetInvoiceRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MerchantInvoiceService>::get_invoice(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetInvoiceSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/billing.invoice.merchant.v1.MerchantInvoiceService/ListInvoices" => {
                    #[allow(non_camel_case_types)]
                    struct ListInvoicesSvc<T: MerchantInvoiceService>(pub Arc<T>);
                    impl<
                        T: MerchantInvoiceService,
                    > tonic::server::UnaryService<super::ListInvoicesRequest>
                    for ListInvoicesSvc<T> {
                        type Response = super::ListInvoicesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListInvoicesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MerchantInvoiceService>::list_invoices(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListInvoicesSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for MerchantInvoiceServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "billing.invoice.merchant.v1.MerchantInvoiceService";
    impl<T> tonic::server::NamedService for MerchantInvoiceServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
