// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PricingPlanPurchase {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub store_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub pricing_plan_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "4")]
    pub transaction_fee_bps: i32,
    #[prost(message, optional, tag = "5")]
    pub transaction_fixed_fee: ::core::option::Option<
        super::super::super::super::shared::types::v1::PricingAmount,
    >,
    #[prost(message, optional, tag = "6")]
    pub monthly_price: ::core::option::Option<
        super::super::super::super::shared::types::v1::PricingAmount,
    >,
    #[prost(
        enumeration = "super::super::shared::v1::PricingPlanPurchaseStatus",
        tag = "7"
    )]
    pub status: i32,
    #[prost(message, optional, tag = "8")]
    pub activated_at: ::core::option::Option<::pbjson_types::Timestamp>,
    #[prost(message, optional, tag = "9")]
    pub current_period_start: ::core::option::Option<::pbjson_types::Timestamp>,
    #[prost(message, optional, tag = "10")]
    pub current_period_end: ::core::option::Option<::pbjson_types::Timestamp>,
    #[prost(message, optional, tag = "11")]
    pub expired_at: ::core::option::Option<::pbjson_types::Timestamp>,
    #[prost(message, optional, tag = "12")]
    pub created_at: ::core::option::Option<::pbjson_types::Timestamp>,
    #[prost(message, optional, tag = "13")]
    pub updated_at: ::core::option::Option<::pbjson_types::Timestamp>,
    #[prost(string, optional, tag = "14")]
    pub payment_intent_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "15")]
    pub checkout_url: ::core::option::Option<::prost::alloc::string::String>,
}
impl ::prost::Name for PricingPlanPurchase {
    const NAME: &'static str = "PricingPlanPurchase";
    const PACKAGE: &'static str = "billing.pricing_plan_purchase.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.pricing_plan_purchase.merchant.v1.PricingPlanPurchase".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.pricing_plan_purchase.merchant.v1.PricingPlanPurchase".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PurchasePricingPlanRequest {
    #[prost(string, tag = "1")]
    pub pricing_plan_id: ::prost::alloc::string::String,
    #[prost(enumeration = "super::super::shared::v1::PaymentMethod", tag = "2")]
    pub payment_method: i32,
}
impl ::prost::Name for PurchasePricingPlanRequest {
    const NAME: &'static str = "PurchasePricingPlanRequest";
    const PACKAGE: &'static str = "billing.pricing_plan_purchase.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.pricing_plan_purchase.merchant.v1.PurchasePricingPlanRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.pricing_plan_purchase.merchant.v1.PurchasePricingPlanRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PurchasePricingPlanResponse {
    #[prost(message, optional, tag = "1")]
    pub pricing_plan_purchase: ::core::option::Option<PricingPlanPurchase>,
}
impl ::prost::Name for PurchasePricingPlanResponse {
    const NAME: &'static str = "PurchasePricingPlanResponse";
    const PACKAGE: &'static str = "billing.pricing_plan_purchase.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.pricing_plan_purchase.merchant.v1.PurchasePricingPlanResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.pricing_plan_purchase.merchant.v1.PurchasePricingPlanResponse".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPricingPlanPurchaseRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
impl ::prost::Name for GetPricingPlanPurchaseRequest {
    const NAME: &'static str = "GetPricingPlanPurchaseRequest";
    const PACKAGE: &'static str = "billing.pricing_plan_purchase.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.pricing_plan_purchase.merchant.v1.GetPricingPlanPurchaseRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.pricing_plan_purchase.merchant.v1.GetPricingPlanPurchaseRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPricingPlanPurchaseResponse {
    #[prost(message, optional, tag = "1")]
    pub pricing_plan_purchase: ::core::option::Option<PricingPlanPurchase>,
}
impl ::prost::Name for GetPricingPlanPurchaseResponse {
    const NAME: &'static str = "GetPricingPlanPurchaseResponse";
    const PACKAGE: &'static str = "billing.pricing_plan_purchase.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.pricing_plan_purchase.merchant.v1.GetPricingPlanPurchaseResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.pricing_plan_purchase.merchant.v1.GetPricingPlanPurchaseResponse"
            .into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListPricingPlanPurchasesRequest {
    #[prost(
        enumeration = "super::super::shared::v1::PricingPlanPurchaseStatus",
        repeated,
        tag = "1"
    )]
    pub status: ::prost::alloc::vec::Vec<i32>,
}
impl ::prost::Name for ListPricingPlanPurchasesRequest {
    const NAME: &'static str = "ListPricingPlanPurchasesRequest";
    const PACKAGE: &'static str = "billing.pricing_plan_purchase.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.pricing_plan_purchase.merchant.v1.ListPricingPlanPurchasesRequest"
            .into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.pricing_plan_purchase.merchant.v1.ListPricingPlanPurchasesRequest"
            .into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListPricingPlanPurchasesResponse {
    #[prost(message, repeated, tag = "1")]
    pub pricing_plan_purchases: ::prost::alloc::vec::Vec<PricingPlanPurchase>,
}
impl ::prost::Name for ListPricingPlanPurchasesResponse {
    const NAME: &'static str = "ListPricingPlanPurchasesResponse";
    const PACKAGE: &'static str = "billing.pricing_plan_purchase.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "billing.pricing_plan_purchase.merchant.v1.ListPricingPlanPurchasesResponse"
            .into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/billing.pricing_plan_purchase.merchant.v1.ListPricingPlanPurchasesResponse"
            .into()
    }
}
/// Generated client implementations.
pub mod pricing_plan_purchase_merchant_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct PricingPlanPurchaseMerchantServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl PricingPlanPurchaseMerchantServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> PricingPlanPurchaseMerchantServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> PricingPlanPurchaseMerchantServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            PricingPlanPurchaseMerchantServiceClient::new(
                InterceptedService::new(inner, interceptor),
            )
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn purchase_pricing_plan(
            &mut self,
            request: impl tonic::IntoRequest<super::PurchasePricingPlanRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PurchasePricingPlanResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/billing.pricing_plan_purchase.merchant.v1.PricingPlanPurchaseMerchantService/PurchasePricingPlan",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "billing.pricing_plan_purchase.merchant.v1.PricingPlanPurchaseMerchantService",
                        "PurchasePricingPlan",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_pricing_plan_purchase(
            &mut self,
            request: impl tonic::IntoRequest<super::GetPricingPlanPurchaseRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetPricingPlanPurchaseResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/billing.pricing_plan_purchase.merchant.v1.PricingPlanPurchaseMerchantService/GetPricingPlanPurchase",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "billing.pricing_plan_purchase.merchant.v1.PricingPlanPurchaseMerchantService",
                        "GetPricingPlanPurchase",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_pricing_plan_purchases(
            &mut self,
            request: impl tonic::IntoRequest<super::ListPricingPlanPurchasesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListPricingPlanPurchasesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/billing.pricing_plan_purchase.merchant.v1.PricingPlanPurchaseMerchantService/ListPricingPlanPurchases",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "billing.pricing_plan_purchase.merchant.v1.PricingPlanPurchaseMerchantService",
                        "ListPricingPlanPurchases",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod pricing_plan_purchase_merchant_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with PricingPlanPurchaseMerchantServiceServer.
    #[async_trait]
    pub trait PricingPlanPurchaseMerchantService: std::marker::Send + std::marker::Sync + 'static {
        async fn purchase_pricing_plan(
            &self,
            request: tonic::Request<super::PurchasePricingPlanRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PurchasePricingPlanResponse>,
            tonic::Status,
        >;
        async fn get_pricing_plan_purchase(
            &self,
            request: tonic::Request<super::GetPricingPlanPurchaseRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetPricingPlanPurchaseResponse>,
            tonic::Status,
        >;
        async fn list_pricing_plan_purchases(
            &self,
            request: tonic::Request<super::ListPricingPlanPurchasesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListPricingPlanPurchasesResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct PricingPlanPurchaseMerchantServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> PricingPlanPurchaseMerchantServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for PricingPlanPurchaseMerchantServiceServer<T>
    where
        T: PricingPlanPurchaseMerchantService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/billing.pricing_plan_purchase.merchant.v1.PricingPlanPurchaseMerchantService/PurchasePricingPlan" => {
                    #[allow(non_camel_case_types)]
                    struct PurchasePricingPlanSvc<T: PricingPlanPurchaseMerchantService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: PricingPlanPurchaseMerchantService,
                    > tonic::server::UnaryService<super::PurchasePricingPlanRequest>
                    for PurchasePricingPlanSvc<T> {
                        type Response = super::PurchasePricingPlanResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PurchasePricingPlanRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PricingPlanPurchaseMerchantService>::purchase_pricing_plan(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PurchasePricingPlanSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/billing.pricing_plan_purchase.merchant.v1.PricingPlanPurchaseMerchantService/GetPricingPlanPurchase" => {
                    #[allow(non_camel_case_types)]
                    struct GetPricingPlanPurchaseSvc<
                        T: PricingPlanPurchaseMerchantService,
                    >(
                        pub Arc<T>,
                    );
                    impl<
                        T: PricingPlanPurchaseMerchantService,
                    > tonic::server::UnaryService<super::GetPricingPlanPurchaseRequest>
                    for GetPricingPlanPurchaseSvc<T> {
                        type Response = super::GetPricingPlanPurchaseResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetPricingPlanPurchaseRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PricingPlanPurchaseMerchantService>::get_pricing_plan_purchase(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetPricingPlanPurchaseSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/billing.pricing_plan_purchase.merchant.v1.PricingPlanPurchaseMerchantService/ListPricingPlanPurchases" => {
                    #[allow(non_camel_case_types)]
                    struct ListPricingPlanPurchasesSvc<
                        T: PricingPlanPurchaseMerchantService,
                    >(
                        pub Arc<T>,
                    );
                    impl<
                        T: PricingPlanPurchaseMerchantService,
                    > tonic::server::UnaryService<super::ListPricingPlanPurchasesRequest>
                    for ListPricingPlanPurchasesSvc<T> {
                        type Response = super::ListPricingPlanPurchasesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::ListPricingPlanPurchasesRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PricingPlanPurchaseMerchantService>::list_pricing_plan_purchases(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListPricingPlanPurchasesSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for PricingPlanPurchaseMerchantServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "billing.pricing_plan_purchase.merchant.v1.PricingPlanPurchaseMerchantService";
    impl<T> tonic::server::NamedService for PricingPlanPurchaseMerchantServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
