// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginRequest {
    #[prost(string, tag = "1")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
}
impl ::prost::Name for LoginRequest {
    const NAME: &'static str = "LoginRequest";
    const PACKAGE: &'static str = "identity.auth.admin.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "identity.auth.admin.v1.LoginRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/identity.auth.admin.v1.LoginRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginResponse {}
impl ::prost::Name for LoginResponse {
    const NAME: &'static str = "LoginResponse";
    const PACKAGE: &'static str = "identity.auth.admin.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "identity.auth.admin.v1.LoginResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/identity.auth.admin.v1.LoginResponse".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogoutRequest {}
impl ::prost::Name for LogoutRequest {
    const NAME: &'static str = "LogoutRequest";
    const PACKAGE: &'static str = "identity.auth.admin.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "identity.auth.admin.v1.LogoutRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/identity.auth.admin.v1.LogoutRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogoutResponse {}
impl ::prost::Name for LogoutResponse {
    const NAME: &'static str = "LogoutResponse";
    const PACKAGE: &'static str = "identity.auth.admin.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "identity.auth.admin.v1.LogoutResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/identity.auth.admin.v1.LogoutResponse".into()
    }
}
/// LoginWithGoogle
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginWithGoogleRequest {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
}
impl ::prost::Name for LoginWithGoogleRequest {
    const NAME: &'static str = "LoginWithGoogleRequest";
    const PACKAGE: &'static str = "identity.auth.admin.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "identity.auth.admin.v1.LoginWithGoogleRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/identity.auth.admin.v1.LoginWithGoogleRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginWithGoogleResponse {}
impl ::prost::Name for LoginWithGoogleResponse {
    const NAME: &'static str = "LoginWithGoogleResponse";
    const PACKAGE: &'static str = "identity.auth.admin.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "identity.auth.admin.v1.LoginWithGoogleResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/identity.auth.admin.v1.LoginWithGoogleResponse".into()
    }
}
/// LoginWithGithub
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginWithGithubRequest {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
}
impl ::prost::Name for LoginWithGithubRequest {
    const NAME: &'static str = "LoginWithGithubRequest";
    const PACKAGE: &'static str = "identity.auth.admin.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "identity.auth.admin.v1.LoginWithGithubRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/identity.auth.admin.v1.LoginWithGithubRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginWithGithubResponse {}
impl ::prost::Name for LoginWithGithubResponse {
    const NAME: &'static str = "LoginWithGithubResponse";
    const PACKAGE: &'static str = "identity.auth.admin.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "identity.auth.admin.v1.LoginWithGithubResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/identity.auth.admin.v1.LoginWithGithubResponse".into()
    }
}
/// Generated client implementations.
pub mod admin_auth_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct AdminAuthServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl AdminAuthServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> AdminAuthServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> AdminAuthServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            AdminAuthServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn login(
            &mut self,
            request: impl tonic::IntoRequest<super::LoginRequest>,
        ) -> std::result::Result<tonic::Response<super::LoginResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/identity.auth.admin.v1.AdminAuthService/Login",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("identity.auth.admin.v1.AdminAuthService", "Login"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn logout(
            &mut self,
            request: impl tonic::IntoRequest<super::LogoutRequest>,
        ) -> std::result::Result<tonic::Response<super::LogoutResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/identity.auth.admin.v1.AdminAuthService/Logout",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("identity.auth.admin.v1.AdminAuthService", "Logout"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn login_with_google(
            &mut self,
            request: impl tonic::IntoRequest<super::LoginWithGoogleRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LoginWithGoogleResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/identity.auth.admin.v1.AdminAuthService/LoginWithGoogle",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "identity.auth.admin.v1.AdminAuthService",
                        "LoginWithGoogle",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn login_with_github(
            &mut self,
            request: impl tonic::IntoRequest<super::LoginWithGithubRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LoginWithGithubResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/identity.auth.admin.v1.AdminAuthService/LoginWithGithub",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "identity.auth.admin.v1.AdminAuthService",
                        "LoginWithGithub",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod admin_auth_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with AdminAuthServiceServer.
    #[async_trait]
    pub trait AdminAuthService: std::marker::Send + std::marker::Sync + 'static {
        async fn login(
            &self,
            request: tonic::Request<super::LoginRequest>,
        ) -> std::result::Result<tonic::Response<super::LoginResponse>, tonic::Status>;
        async fn logout(
            &self,
            request: tonic::Request<super::LogoutRequest>,
        ) -> std::result::Result<tonic::Response<super::LogoutResponse>, tonic::Status>;
        async fn login_with_google(
            &self,
            request: tonic::Request<super::LoginWithGoogleRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LoginWithGoogleResponse>,
            tonic::Status,
        >;
        async fn login_with_github(
            &self,
            request: tonic::Request<super::LoginWithGithubRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LoginWithGithubResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct AdminAuthServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> AdminAuthServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for AdminAuthServiceServer<T>
    where
        T: AdminAuthService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/identity.auth.admin.v1.AdminAuthService/Login" => {
                    #[allow(non_camel_case_types)]
                    struct LoginSvc<T: AdminAuthService>(pub Arc<T>);
                    impl<
                        T: AdminAuthService,
                    > tonic::server::UnaryService<super::LoginRequest> for LoginSvc<T> {
                        type Response = super::LoginResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LoginRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AdminAuthService>::login(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LoginSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/identity.auth.admin.v1.AdminAuthService/Logout" => {
                    #[allow(non_camel_case_types)]
                    struct LogoutSvc<T: AdminAuthService>(pub Arc<T>);
                    impl<
                        T: AdminAuthService,
                    > tonic::server::UnaryService<super::LogoutRequest>
                    for LogoutSvc<T> {
                        type Response = super::LogoutResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LogoutRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AdminAuthService>::logout(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LogoutSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/identity.auth.admin.v1.AdminAuthService/LoginWithGoogle" => {
                    #[allow(non_camel_case_types)]
                    struct LoginWithGoogleSvc<T: AdminAuthService>(pub Arc<T>);
                    impl<
                        T: AdminAuthService,
                    > tonic::server::UnaryService<super::LoginWithGoogleRequest>
                    for LoginWithGoogleSvc<T> {
                        type Response = super::LoginWithGoogleResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LoginWithGoogleRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AdminAuthService>::login_with_google(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LoginWithGoogleSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/identity.auth.admin.v1.AdminAuthService/LoginWithGithub" => {
                    #[allow(non_camel_case_types)]
                    struct LoginWithGithubSvc<T: AdminAuthService>(pub Arc<T>);
                    impl<
                        T: AdminAuthService,
                    > tonic::server::UnaryService<super::LoginWithGithubRequest>
                    for LoginWithGithubSvc<T> {
                        type Response = super::LoginWithGithubResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LoginWithGithubRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AdminAuthService>::login_with_github(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LoginWithGithubSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for AdminAuthServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "identity.auth.admin.v1.AdminAuthService";
    impl<T> tonic::server::NamedService for AdminAuthServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
