// This file is @generated by prost-build.
/// Registration
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserRegistered {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub email: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub created_at: ::core::option::Option<::pbjson_types::Timestamp>,
    #[prost(message, optional, tag = "99")]
    pub metadata: ::core::option::Option<
        super::super::super::shared::events::v1::EventMetadata,
    >,
}
impl ::prost::Name for UserRegistered {
    const NAME: &'static str = "UserRegistered";
    const PACKAGE: &'static str = "identity.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "identity.events.v1.UserRegistered".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/identity.events.v1.UserRegistered".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginVerificationCreated {
    #[prost(string, tag = "1")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub otp: ::prost::alloc::string::String,
}
impl ::prost::Name for LoginVerificationCreated {
    const NAME: &'static str = "LoginVerificationCreated";
    const PACKAGE: &'static str = "identity.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "identity.events.v1.LoginVerificationCreated".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/identity.events.v1.LoginVerificationCreated".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PasswordResetVerificationCreated {
    #[prost(string, tag = "1")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub otp: ::prost::alloc::string::String,
}
impl ::prost::Name for PasswordResetVerificationCreated {
    const NAME: &'static str = "PasswordResetVerificationCreated";
    const PACKAGE: &'static str = "identity.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "identity.events.v1.PasswordResetVerificationCreated".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/identity.events.v1.PasswordResetVerificationCreated".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChangeEmailVerificationCreated {
    /// new email
    #[prost(string, tag = "1")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub otp: ::prost::alloc::string::String,
}
impl ::prost::Name for ChangeEmailVerificationCreated {
    const NAME: &'static str = "ChangeEmailVerificationCreated";
    const PACKAGE: &'static str = "identity.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "identity.events.v1.ChangeEmailVerificationCreated".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/identity.events.v1.ChangeEmailVerificationCreated".into()
    }
}
/// Login
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginSucceeded {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub provider: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "4")]
    pub ip_address: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub city: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub region: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "7")]
    pub country: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "8")]
    pub browser: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "9")]
    pub os: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "10")]
    pub created_at: ::core::option::Option<::pbjson_types::Timestamp>,
    #[prost(message, optional, tag = "99")]
    pub metadata: ::core::option::Option<
        super::super::super::shared::events::v1::EventMetadata,
    >,
}
impl ::prost::Name for LoginSucceeded {
    const NAME: &'static str = "LoginSucceeded";
    const PACKAGE: &'static str = "identity.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "identity.events.v1.LoginSucceeded".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/identity.events.v1.LoginSucceeded".into()
    }
}
/// Password Reset
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PasswordResetCompleted {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub email: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "99")]
    pub metadata: ::core::option::Option<
        super::super::super::shared::events::v1::EventMetadata,
    >,
}
impl ::prost::Name for PasswordResetCompleted {
    const NAME: &'static str = "PasswordResetCompleted";
    const PACKAGE: &'static str = "identity.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "identity.events.v1.PasswordResetCompleted".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/identity.events.v1.PasswordResetCompleted".into()
    }
}
/// Password Changed
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PasswordChanged {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub email: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "99")]
    pub metadata: ::core::option::Option<
        super::super::super::shared::events::v1::EventMetadata,
    >,
}
impl ::prost::Name for PasswordChanged {
    const NAME: &'static str = "PasswordChanged";
    const PACKAGE: &'static str = "identity.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "identity.events.v1.PasswordChanged".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/identity.events.v1.PasswordChanged".into()
    }
}
/// Two Factor Auth
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TwoFactorAuthEnabled {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub email: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "99")]
    pub metadata: ::core::option::Option<
        super::super::super::shared::events::v1::EventMetadata,
    >,
}
impl ::prost::Name for TwoFactorAuthEnabled {
    const NAME: &'static str = "TwoFactorAuthEnabled";
    const PACKAGE: &'static str = "identity.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "identity.events.v1.TwoFactorAuthEnabled".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/identity.events.v1.TwoFactorAuthEnabled".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TwoFactorAuthDisabled {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub email: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "99")]
    pub metadata: ::core::option::Option<
        super::super::super::shared::events::v1::EventMetadata,
    >,
}
impl ::prost::Name for TwoFactorAuthDisabled {
    const NAME: &'static str = "TwoFactorAuthDisabled";
    const PACKAGE: &'static str = "identity.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "identity.events.v1.TwoFactorAuthDisabled".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/identity.events.v1.TwoFactorAuthDisabled".into()
    }
}
/// Account
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AccountDeletionScheduled {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub email: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "99")]
    pub metadata: ::core::option::Option<
        super::super::super::shared::events::v1::EventMetadata,
    >,
}
impl ::prost::Name for AccountDeletionScheduled {
    const NAME: &'static str = "AccountDeletionScheduled";
    const PACKAGE: &'static str = "identity.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "identity.events.v1.AccountDeletionScheduled".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/identity.events.v1.AccountDeletionScheduled".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AccountDeleted {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub email: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "99")]
    pub metadata: ::core::option::Option<
        super::super::super::shared::events::v1::EventMetadata,
    >,
}
impl ::prost::Name for AccountDeleted {
    const NAME: &'static str = "AccountDeleted";
    const PACKAGE: &'static str = "identity.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "identity.events.v1.AccountDeleted".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/identity.events.v1.AccountDeleted".into()
    }
}
/// Email
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProfileEmailChanged {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub new_email: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub old_email: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "99")]
    pub metadata: ::core::option::Option<
        super::super::super::shared::events::v1::EventMetadata,
    >,
}
impl ::prost::Name for ProfileEmailChanged {
    const NAME: &'static str = "ProfileEmailChanged";
    const PACKAGE: &'static str = "identity.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "identity.events.v1.ProfileEmailChanged".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/identity.events.v1.ProfileEmailChanged".into()
    }
}
/// Security Challenge
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SecurityChallengeOtpRequested {
    #[prost(string, tag = "1")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub otp: ::prost::alloc::string::String,
}
impl ::prost::Name for SecurityChallengeOtpRequested {
    const NAME: &'static str = "SecurityChallengeOtpRequested";
    const PACKAGE: &'static str = "identity.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "identity.events.v1.SecurityChallengeOtpRequested".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/identity.events.v1.SecurityChallengeOtpRequested".into()
    }
}
