// This file is @generated by prost-build.
#[cfg(feature = "billing")]
pub mod billing {
    pub mod currency {
        pub mod v1 {
            include!("billing.currency.v1.rs");
        }
    }
    pub mod deposit_wallet {
        pub mod events {
            pub mod v1 {
                include!("billing.deposit_wallet.events.v1.rs");
            }
        }
        pub mod merchant {
            pub mod v1 {
                include!("billing.deposit_wallet.merchant.v1.rs");
            }
        }
    }
    pub mod invoice {
        pub mod admin {
            pub mod v1 {
                include!("billing.invoice.admin.v1.rs");
            }
        }
        pub mod events {
            pub mod v1 {
                include!("billing.invoice.events.v1.rs");
            }
        }
        pub mod merchant {
            pub mod v1 {
                include!("billing.invoice.merchant.v1.rs");
            }
        }
        pub mod public {
            pub mod v1 {
                include!("billing.invoice.public.v1.rs");
            }
        }
        pub mod realtime {
            pub mod v1 {
                include!("billing.invoice.realtime.v1.rs");
            }
        }
    }
    pub mod payment_intent {
        pub mod admin {
            pub mod v1 {
                include!("billing.payment_intent.admin.v1.rs");
            }
        }
        pub mod events {
            pub mod v1 {
                include!("billing.payment_intent.events.v1.rs");
            }
        }
        pub mod merchant {
            pub mod v1 {
                include!("billing.payment_intent.merchant.v1.rs");
            }
        }
        pub mod public {
            pub mod v1 {
                include!("billing.payment_intent.public.v1.rs");
            }
        }
        pub mod shared {
            pub mod v1 {
                include!("billing.payment_intent.shared.v1.rs");
            }
        }
    }
    pub mod schema {
        pub mod v1 {
            include!("billing.schema.v1.rs");
        }
    }
    pub mod shared {
        pub mod v1 {
            include!("billing.shared.v1.rs");
        }
    }
}
#[cfg(feature = "blockchain")]
pub mod blockchain {
    pub mod events {
        pub mod v1 {
            include!("blockchain.events.v1.rs");
        }
    }
}
#[cfg(feature = "identity")]
pub mod identity {
    pub mod auth {
        pub mod admin {
            pub mod v1 {
                include!("identity.auth.admin.v1.rs");
            }
        }
        pub mod merchant {
            pub mod v1 {
                include!("identity.auth.merchant.v1.rs");
            }
        }
        pub mod shared {
            pub mod v1 {
                include!("identity.auth.shared.v1.rs");
            }
        }
    }
    pub mod events {
        pub mod v1 {
            include!("identity.events.v1.rs");
        }
    }
    pub mod role {
        pub mod admin {
            pub mod v1 {
                include!("identity.role.admin.v1.rs");
            }
        }
    }
    pub mod security {
        pub mod v1 {
            include!("identity.security.v1.rs");
        }
    }
    pub mod session {
        pub mod admin {
            pub mod v1 {
                include!("identity.session.admin.v1.rs");
            }
        }
        pub mod merchant {
            pub mod v1 {
                include!("identity.session.merchant.v1.rs");
            }
        }
    }
    pub mod shared {
        pub mod v1 {
            include!("identity.shared.v1.rs");
        }
    }
    pub mod staff {
        pub mod admin {
            pub mod v1 {
                include!("identity.staff.admin.v1.rs");
            }
        }
    }
}
#[cfg(feature = "indexer")]
pub mod indexer {
    pub mod v1 {
        include!("indexer.v1.rs");
    }
}
#[cfg(feature = "payout")]
pub mod payout {
    pub mod events {
        pub mod v1 {
            include!("payout.events.v1.rs");
        }
    }
    pub mod gas_wallet {
        pub mod events {
            pub mod v1 {
                include!("payout.gas_wallet.events.v1.rs");
            }
        }
        pub mod merchant {
            pub mod v1 {
                include!("payout.gas_wallet.merchant.v1.rs");
            }
        }
    }
    pub mod metadata {
        pub mod v1 {
            include!("payout.metadata.v1.rs");
        }
    }
    pub mod payout {
        pub mod admin {
            pub mod v1 {
                include!("payout.payout.admin.v1.rs");
            }
        }
        pub mod merchant {
            pub mod v1 {
                include!("payout.payout.merchant.v1.rs");
            }
        }
    }
    pub mod payout_wallet {
        pub mod events {
            pub mod v1 {
                include!("payout.payout_wallet.events.v1.rs");
            }
        }
        pub mod merchant {
            pub mod v1 {
                include!("payout.payout_wallet.merchant.v1.rs");
            }
        }
    }
    pub mod schema {
        pub mod v1 {
            include!("payout.schema.v1.rs");
        }
    }
    pub mod shared {
        pub mod v1 {
            include!("payout.shared.v1.rs");
        }
    }
    pub mod transfer {
        pub mod events {
            pub mod v1 {
                include!("payout.transfer.events.v1.rs");
            }
        }
    }
}
#[cfg(feature = "realtime")]
pub mod realtime {
    pub mod v1 {
        include!("realtime.v1.rs");
    }
}
#[cfg(feature = "shared")]
pub mod shared {
    pub mod admin {
        pub mod v1 {
            include!("shared.admin.v1.rs");
        }
    }
    pub mod enums {
        pub mod v1 {
            include!("shared.enums.v1.rs");
        }
    }
    pub mod events {
        pub mod v1 {
            include!("shared.events.v1.rs");
        }
    }
    pub mod schema {
        pub mod v1 {
            include!("shared.schema.v1.rs");
        }
    }
    pub mod types {
        pub mod v1 {
            include!("shared.types.v1.rs");
        }
    }
}
#[cfg(feature = "store")]
pub mod store {
    pub mod api_key {
        pub mod events {
            pub mod v1 {
                include!("store.api_key.events.v1.rs");
            }
        }
        pub mod merchant {
            pub mod v1 {
                include!("store.api_key.merchant.v1.rs");
            }
        }
    }
    pub mod metadata {
        pub mod v1 {
            include!("store.metadata.v1.rs");
        }
    }
    pub mod schema {
        pub mod v1 {
            include!("store.schema.v1.rs");
        }
    }
    pub mod store {
        pub mod admin {
            pub mod v1 {
                include!("store.store.admin.v1.rs");
            }
        }
        pub mod common {
            pub mod v1 {
                include!("store.store.common.v1.rs");
            }
        }
        pub mod events {
            pub mod v1 {
                include!("store.store.events.v1.rs");
            }
        }
        pub mod merchant {
            pub mod v1 {
                include!("store.store.merchant.v1.rs");
            }
        }
    }
    pub mod store_currency {
        pub mod events {
            pub mod v1 {
                include!("store.store_currency.events.v1.rs");
            }
        }
        pub mod internal {
            pub mod v1 {
                include!("store.store_currency.internal.v1.rs");
            }
        }
        pub mod merchant {
            pub mod v1 {
                include!("store.store_currency.merchant.v1.rs");
            }
        }
    }
}
#[cfg(feature = "support")]
pub mod support {
    pub mod category {
        pub mod admin {
            pub mod v1 {
                include!("support.category.admin.v1.rs");
            }
        }
        pub mod merchant {
            pub mod v1 {
                include!("support.category.merchant.v1.rs");
            }
        }
    }
    pub mod schema {
        pub mod v1 {
            include!("support.schema.v1.rs");
        }
    }
    pub mod shared {
        pub mod v1 {
            include!("support.shared.v1.rs");
        }
    }
    pub mod staff {
        pub mod admin {
            pub mod v1 {
                include!("support.staff.admin.v1.rs");
            }
        }
        pub mod merchant {
            pub mod v1 {
                include!("support.staff.merchant.v1.rs");
            }
        }
    }
    pub mod ticket {
        pub mod admin {
            pub mod v1 {
                include!("support.ticket.admin.v1.rs");
            }
        }
        pub mod merchant {
            pub mod v1 {
                include!("support.ticket.merchant.v1.rs");
            }
        }
    }
}
#[cfg(feature = "user")]
pub mod user {
    pub mod admin {
        pub mod v1 {
            include!("user.admin.v1.rs");
        }
    }
    pub mod events {
        pub mod v1 {
            include!("user.events.v1.rs");
        }
    }
    pub mod merchant {
        pub mod v1 {
            include!("user.merchant.v1.rs");
        }
    }
    pub mod schema {
        pub mod v1 {
            include!("user.schema.v1.rs");
        }
    }
    pub mod shared {
        pub mod v1 {
            include!("user.shared.v1.rs");
        }
    }
}
#[cfg(feature = "verification")]
pub mod verification {
    pub mod v1 {
        include!("verification.v1.rs");
    }
}
#[cfg(feature = "wallet")]
pub mod wallet {
    pub mod v1 {
        include!("wallet.v1.rs");
    }
}
#[cfg(feature = "webhook")]
pub mod webhook {
    pub mod delivery {
        pub mod merchant {
            pub mod v1 {
                include!("webhook.delivery.merchant.v1.rs");
            }
        }
    }
    pub mod merchant {
        pub mod v1 {
            include!("webhook.merchant.v1.rs");
        }
    }
    pub mod metadata {
        pub mod v1 {
            include!("webhook.metadata.v1.rs");
        }
    }
    pub mod schema {
        pub mod v1 {
            include!("webhook.schema.v1.rs");
        }
    }
    pub mod shared {
        pub mod v1 {
            include!("webhook.shared.v1.rs");
        }
    }
}
