// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BatchPayoutItem {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub address: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub amount: ::prost::alloc::string::String,
}
impl ::prost::Name for BatchPayoutItem {
    const NAME: &'static str = "BatchPayoutItem";
    const PACKAGE: &'static str = "payout.batch_payout.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "payout.batch_payout.merchant.v1.BatchPayoutItem".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/payout.batch_payout.merchant.v1.BatchPayoutItem".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchPayout {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(
        enumeration = "super::super::super::super::shared::enums::v1::PricingCurrency",
        tag = "4"
    )]
    pub pricing_currency: i32,
    #[prost(
        enumeration = "super::super::super::super::shared::enums::v1::NetworkId",
        tag = "5"
    )]
    pub network_id: i32,
    #[prost(
        enumeration = "super::super::super::super::shared::enums::v1::PaymentCurrency",
        tag = "6"
    )]
    pub currency: i32,
    #[prost(message, repeated, tag = "7")]
    pub items: ::prost::alloc::vec::Vec<BatchPayoutItem>,
    #[prost(enumeration = "BatchPayoutStatus", tag = "8")]
    pub status: i32,
    #[prost(message, optional, tag = "9")]
    pub created_at: ::core::option::Option<::pbjson_types::Timestamp>,
    #[prost(message, optional, tag = "10")]
    pub updated_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
impl ::prost::Name for BatchPayout {
    const NAME: &'static str = "BatchPayout";
    const PACKAGE: &'static str = "payout.batch_payout.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "payout.batch_payout.merchant.v1.BatchPayout".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/payout.batch_payout.merchant.v1.BatchPayout".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetBatchPayoutRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
impl ::prost::Name for GetBatchPayoutRequest {
    const NAME: &'static str = "GetBatchPayoutRequest";
    const PACKAGE: &'static str = "payout.batch_payout.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "payout.batch_payout.merchant.v1.GetBatchPayoutRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/payout.batch_payout.merchant.v1.GetBatchPayoutRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBatchPayoutResponse {
    #[prost(message, optional, tag = "1")]
    pub batch_payout: ::core::option::Option<BatchPayout>,
}
impl ::prost::Name for GetBatchPayoutResponse {
    const NAME: &'static str = "GetBatchPayoutResponse";
    const PACKAGE: &'static str = "payout.batch_payout.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "payout.batch_payout.merchant.v1.GetBatchPayoutResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/payout.batch_payout.merchant.v1.GetBatchPayoutResponse".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListBatchPayoutsRequest {}
impl ::prost::Name for ListBatchPayoutsRequest {
    const NAME: &'static str = "ListBatchPayoutsRequest";
    const PACKAGE: &'static str = "payout.batch_payout.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "payout.batch_payout.merchant.v1.ListBatchPayoutsRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/payout.batch_payout.merchant.v1.ListBatchPayoutsRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListBatchPayoutsResponse {
    #[prost(message, repeated, tag = "1")]
    pub batch_payouts: ::prost::alloc::vec::Vec<BatchPayout>,
}
impl ::prost::Name for ListBatchPayoutsResponse {
    const NAME: &'static str = "ListBatchPayoutsResponse";
    const PACKAGE: &'static str = "payout.batch_payout.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "payout.batch_payout.merchant.v1.ListBatchPayoutsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/payout.batch_payout.merchant.v1.ListBatchPayoutsResponse".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateBatchPayoutRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(
        enumeration = "super::super::super::super::shared::enums::v1::PricingCurrency",
        tag = "3"
    )]
    pub pricing_currency: i32,
    #[prost(
        enumeration = "super::super::super::super::shared::enums::v1::NetworkId",
        tag = "4"
    )]
    pub network_id: i32,
    #[prost(
        enumeration = "super::super::super::super::shared::enums::v1::PaymentCurrency",
        tag = "5"
    )]
    pub currency: i32,
    #[prost(message, repeated, tag = "6")]
    pub items: ::prost::alloc::vec::Vec<BatchPayoutItem>,
}
impl ::prost::Name for CreateBatchPayoutRequest {
    const NAME: &'static str = "CreateBatchPayoutRequest";
    const PACKAGE: &'static str = "payout.batch_payout.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "payout.batch_payout.merchant.v1.CreateBatchPayoutRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/payout.batch_payout.merchant.v1.CreateBatchPayoutRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateBatchPayoutResponse {}
impl ::prost::Name for CreateBatchPayoutResponse {
    const NAME: &'static str = "CreateBatchPayoutResponse";
    const PACKAGE: &'static str = "payout.batch_payout.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "payout.batch_payout.merchant.v1.CreateBatchPayoutResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/payout.batch_payout.merchant.v1.CreateBatchPayoutResponse".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteBatchPayoutRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
impl ::prost::Name for DeleteBatchPayoutRequest {
    const NAME: &'static str = "DeleteBatchPayoutRequest";
    const PACKAGE: &'static str = "payout.batch_payout.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "payout.batch_payout.merchant.v1.DeleteBatchPayoutRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/payout.batch_payout.merchant.v1.DeleteBatchPayoutRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteBatchPayoutResponse {}
impl ::prost::Name for DeleteBatchPayoutResponse {
    const NAME: &'static str = "DeleteBatchPayoutResponse";
    const PACKAGE: &'static str = "payout.batch_payout.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "payout.batch_payout.merchant.v1.DeleteBatchPayoutResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/payout.batch_payout.merchant.v1.DeleteBatchPayoutResponse".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RetryBatchPayoutRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
impl ::prost::Name for RetryBatchPayoutRequest {
    const NAME: &'static str = "RetryBatchPayoutRequest";
    const PACKAGE: &'static str = "payout.batch_payout.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "payout.batch_payout.merchant.v1.RetryBatchPayoutRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/payout.batch_payout.merchant.v1.RetryBatchPayoutRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RetryBatchPayoutResponse {
    #[prost(message, optional, tag = "1")]
    pub batch_payout: ::core::option::Option<BatchPayout>,
}
impl ::prost::Name for RetryBatchPayoutResponse {
    const NAME: &'static str = "RetryBatchPayoutResponse";
    const PACKAGE: &'static str = "payout.batch_payout.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "payout.batch_payout.merchant.v1.RetryBatchPayoutResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/payout.batch_payout.merchant.v1.RetryBatchPayoutResponse".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BatchPayoutStatus {
    Unspecified = 0,
    Ready = 1,
    Processing = 2,
    Completed = 3,
    PartiallyCompleted = 4,
    Failed = 5,
    Cancelled = 6,
}
impl BatchPayoutStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "BATCH_PAYOUT_STATUS_UNSPECIFIED",
            Self::Ready => "BATCH_PAYOUT_STATUS_READY",
            Self::Processing => "BATCH_PAYOUT_STATUS_PROCESSING",
            Self::Completed => "BATCH_PAYOUT_STATUS_COMPLETED",
            Self::PartiallyCompleted => "BATCH_PAYOUT_STATUS_PARTIALLY_COMPLETED",
            Self::Failed => "BATCH_PAYOUT_STATUS_FAILED",
            Self::Cancelled => "BATCH_PAYOUT_STATUS_CANCELLED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BATCH_PAYOUT_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "BATCH_PAYOUT_STATUS_READY" => Some(Self::Ready),
            "BATCH_PAYOUT_STATUS_PROCESSING" => Some(Self::Processing),
            "BATCH_PAYOUT_STATUS_COMPLETED" => Some(Self::Completed),
            "BATCH_PAYOUT_STATUS_PARTIALLY_COMPLETED" => Some(Self::PartiallyCompleted),
            "BATCH_PAYOUT_STATUS_FAILED" => Some(Self::Failed),
            "BATCH_PAYOUT_STATUS_CANCELLED" => Some(Self::Cancelled),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod merchant_batch_payout_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct MerchantBatchPayoutServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl MerchantBatchPayoutServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> MerchantBatchPayoutServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> MerchantBatchPayoutServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            MerchantBatchPayoutServiceClient::new(
                InterceptedService::new(inner, interceptor),
            )
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn get_batch_payout(
            &mut self,
            request: impl tonic::IntoRequest<super::GetBatchPayoutRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetBatchPayoutResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/payout.batch_payout.merchant.v1.MerchantBatchPayoutService/GetBatchPayout",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "payout.batch_payout.merchant.v1.MerchantBatchPayoutService",
                        "GetBatchPayout",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_batch_payouts(
            &mut self,
            request: impl tonic::IntoRequest<super::ListBatchPayoutsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListBatchPayoutsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/payout.batch_payout.merchant.v1.MerchantBatchPayoutService/ListBatchPayouts",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "payout.batch_payout.merchant.v1.MerchantBatchPayoutService",
                        "ListBatchPayouts",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn create_batch_payout(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateBatchPayoutRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateBatchPayoutResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/payout.batch_payout.merchant.v1.MerchantBatchPayoutService/CreateBatchPayout",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "payout.batch_payout.merchant.v1.MerchantBatchPayoutService",
                        "CreateBatchPayout",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn delete_batch_payout(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteBatchPayoutRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteBatchPayoutResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/payout.batch_payout.merchant.v1.MerchantBatchPayoutService/DeleteBatchPayout",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "payout.batch_payout.merchant.v1.MerchantBatchPayoutService",
                        "DeleteBatchPayout",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn retry_batch_payout(
            &mut self,
            request: impl tonic::IntoRequest<super::RetryBatchPayoutRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RetryBatchPayoutResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/payout.batch_payout.merchant.v1.MerchantBatchPayoutService/RetryBatchPayout",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "payout.batch_payout.merchant.v1.MerchantBatchPayoutService",
                        "RetryBatchPayout",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod merchant_batch_payout_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with MerchantBatchPayoutServiceServer.
    #[async_trait]
    pub trait MerchantBatchPayoutService: std::marker::Send + std::marker::Sync + 'static {
        async fn get_batch_payout(
            &self,
            request: tonic::Request<super::GetBatchPayoutRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetBatchPayoutResponse>,
            tonic::Status,
        >;
        async fn list_batch_payouts(
            &self,
            request: tonic::Request<super::ListBatchPayoutsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListBatchPayoutsResponse>,
            tonic::Status,
        >;
        async fn create_batch_payout(
            &self,
            request: tonic::Request<super::CreateBatchPayoutRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateBatchPayoutResponse>,
            tonic::Status,
        >;
        async fn delete_batch_payout(
            &self,
            request: tonic::Request<super::DeleteBatchPayoutRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteBatchPayoutResponse>,
            tonic::Status,
        >;
        async fn retry_batch_payout(
            &self,
            request: tonic::Request<super::RetryBatchPayoutRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RetryBatchPayoutResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct MerchantBatchPayoutServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> MerchantBatchPayoutServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for MerchantBatchPayoutServiceServer<T>
    where
        T: MerchantBatchPayoutService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/payout.batch_payout.merchant.v1.MerchantBatchPayoutService/GetBatchPayout" => {
                    #[allow(non_camel_case_types)]
                    struct GetBatchPayoutSvc<T: MerchantBatchPayoutService>(pub Arc<T>);
                    impl<
                        T: MerchantBatchPayoutService,
                    > tonic::server::UnaryService<super::GetBatchPayoutRequest>
                    for GetBatchPayoutSvc<T> {
                        type Response = super::GetBatchPayoutResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetBatchPayoutRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MerchantBatchPayoutService>::get_batch_payout(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetBatchPayoutSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/payout.batch_payout.merchant.v1.MerchantBatchPayoutService/ListBatchPayouts" => {
                    #[allow(non_camel_case_types)]
                    struct ListBatchPayoutsSvc<T: MerchantBatchPayoutService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: MerchantBatchPayoutService,
                    > tonic::server::UnaryService<super::ListBatchPayoutsRequest>
                    for ListBatchPayoutsSvc<T> {
                        type Response = super::ListBatchPayoutsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListBatchPayoutsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MerchantBatchPayoutService>::list_batch_payouts(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListBatchPayoutsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/payout.batch_payout.merchant.v1.MerchantBatchPayoutService/CreateBatchPayout" => {
                    #[allow(non_camel_case_types)]
                    struct CreateBatchPayoutSvc<T: MerchantBatchPayoutService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: MerchantBatchPayoutService,
                    > tonic::server::UnaryService<super::CreateBatchPayoutRequest>
                    for CreateBatchPayoutSvc<T> {
                        type Response = super::CreateBatchPayoutResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateBatchPayoutRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MerchantBatchPayoutService>::create_batch_payout(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateBatchPayoutSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/payout.batch_payout.merchant.v1.MerchantBatchPayoutService/DeleteBatchPayout" => {
                    #[allow(non_camel_case_types)]
                    struct DeleteBatchPayoutSvc<T: MerchantBatchPayoutService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: MerchantBatchPayoutService,
                    > tonic::server::UnaryService<super::DeleteBatchPayoutRequest>
                    for DeleteBatchPayoutSvc<T> {
                        type Response = super::DeleteBatchPayoutResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeleteBatchPayoutRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MerchantBatchPayoutService>::delete_batch_payout(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeleteBatchPayoutSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/payout.batch_payout.merchant.v1.MerchantBatchPayoutService/RetryBatchPayout" => {
                    #[allow(non_camel_case_types)]
                    struct RetryBatchPayoutSvc<T: MerchantBatchPayoutService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: MerchantBatchPayoutService,
                    > tonic::server::UnaryService<super::RetryBatchPayoutRequest>
                    for RetryBatchPayoutSvc<T> {
                        type Response = super::RetryBatchPayoutResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RetryBatchPayoutRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MerchantBatchPayoutService>::retry_batch_payout(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RetryBatchPayoutSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for MerchantBatchPayoutServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "payout.batch_payout.merchant.v1.MerchantBatchPayoutService";
    impl<T> tonic::server::NamedService for MerchantBatchPayoutServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
