// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchPayout {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub store_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "4")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(
        enumeration = "super::super::super::super::shared::enums::v1::PricingCurrency",
        tag = "5"
    )]
    pub pricing_currency: i32,
    #[prost(
        enumeration = "super::super::super::super::shared::enums::v1::NetworkId",
        tag = "6"
    )]
    pub network_id: i32,
    #[prost(
        enumeration = "super::super::super::super::shared::enums::v1::PaymentCurrency",
        tag = "7"
    )]
    pub currency: i32,
    #[prost(message, repeated, tag = "8")]
    pub items: ::prost::alloc::vec::Vec<super::super::merchant::v1::BatchPayoutItem>,
    #[prost(enumeration = "super::super::merchant::v1::BatchPayoutStatus", tag = "9")]
    pub status: i32,
    #[prost(message, optional, tag = "10")]
    pub created_at: ::core::option::Option<::pbjson_types::Timestamp>,
    #[prost(message, optional, tag = "11")]
    pub updated_at: ::core::option::Option<::pbjson_types::Timestamp>,
    #[prost(message, optional, tag = "12")]
    pub store: ::core::option::Option<
        super::super::super::super::shared::admin::v1::Store,
    >,
}
impl ::prost::Name for BatchPayout {
    const NAME: &'static str = "BatchPayout";
    const PACKAGE: &'static str = "payout.batch_payout.admin.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "payout.batch_payout.admin.v1.BatchPayout".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/payout.batch_payout.admin.v1.BatchPayout".into()
    }
}
/// ======= GetBatchPayout =======
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetBatchPayoutRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
impl ::prost::Name for GetBatchPayoutRequest {
    const NAME: &'static str = "GetBatchPayoutRequest";
    const PACKAGE: &'static str = "payout.batch_payout.admin.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "payout.batch_payout.admin.v1.GetBatchPayoutRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/payout.batch_payout.admin.v1.GetBatchPayoutRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBatchPayoutResponse {
    #[prost(message, optional, tag = "1")]
    pub batch_payout: ::core::option::Option<BatchPayout>,
}
impl ::prost::Name for GetBatchPayoutResponse {
    const NAME: &'static str = "GetBatchPayoutResponse";
    const PACKAGE: &'static str = "payout.batch_payout.admin.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "payout.batch_payout.admin.v1.GetBatchPayoutResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/payout.batch_payout.admin.v1.GetBatchPayoutResponse".into()
    }
}
/// ======= ListBatchPayouts =======
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListBatchPayoutsRequest {
    #[prost(string, optional, tag = "1")]
    pub store_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub user_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(
        enumeration = "super::super::merchant::v1::BatchPayoutStatus",
        repeated,
        tag = "3"
    )]
    pub status: ::prost::alloc::vec::Vec<i32>,
}
impl ::prost::Name for ListBatchPayoutsRequest {
    const NAME: &'static str = "ListBatchPayoutsRequest";
    const PACKAGE: &'static str = "payout.batch_payout.admin.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "payout.batch_payout.admin.v1.ListBatchPayoutsRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/payout.batch_payout.admin.v1.ListBatchPayoutsRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListBatchPayoutsResponse {
    #[prost(message, repeated, tag = "1")]
    pub batch_payouts: ::prost::alloc::vec::Vec<BatchPayout>,
}
impl ::prost::Name for ListBatchPayoutsResponse {
    const NAME: &'static str = "ListBatchPayoutsResponse";
    const PACKAGE: &'static str = "payout.batch_payout.admin.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "payout.batch_payout.admin.v1.ListBatchPayoutsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/payout.batch_payout.admin.v1.ListBatchPayoutsResponse".into()
    }
}
/// ======= RetryBatchPayout =======
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RetryBatchPayoutRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
impl ::prost::Name for RetryBatchPayoutRequest {
    const NAME: &'static str = "RetryBatchPayoutRequest";
    const PACKAGE: &'static str = "payout.batch_payout.admin.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "payout.batch_payout.admin.v1.RetryBatchPayoutRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/payout.batch_payout.admin.v1.RetryBatchPayoutRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RetryBatchPayoutResponse {
    #[prost(message, optional, tag = "1")]
    pub batch_payout: ::core::option::Option<BatchPayout>,
}
impl ::prost::Name for RetryBatchPayoutResponse {
    const NAME: &'static str = "RetryBatchPayoutResponse";
    const PACKAGE: &'static str = "payout.batch_payout.admin.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "payout.batch_payout.admin.v1.RetryBatchPayoutResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/payout.batch_payout.admin.v1.RetryBatchPayoutResponse".into()
    }
}
/// Generated client implementations.
pub mod admin_batch_payout_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct AdminBatchPayoutServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl AdminBatchPayoutServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> AdminBatchPayoutServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> AdminBatchPayoutServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            AdminBatchPayoutServiceClient::new(
                InterceptedService::new(inner, interceptor),
            )
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn get_batch_payout(
            &mut self,
            request: impl tonic::IntoRequest<super::GetBatchPayoutRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetBatchPayoutResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/payout.batch_payout.admin.v1.AdminBatchPayoutService/GetBatchPayout",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "payout.batch_payout.admin.v1.AdminBatchPayoutService",
                        "GetBatchPayout",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_batch_payouts(
            &mut self,
            request: impl tonic::IntoRequest<super::ListBatchPayoutsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListBatchPayoutsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/payout.batch_payout.admin.v1.AdminBatchPayoutService/ListBatchPayouts",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "payout.batch_payout.admin.v1.AdminBatchPayoutService",
                        "ListBatchPayouts",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn retry_batch_payout(
            &mut self,
            request: impl tonic::IntoRequest<super::RetryBatchPayoutRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RetryBatchPayoutResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/payout.batch_payout.admin.v1.AdminBatchPayoutService/RetryBatchPayout",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "payout.batch_payout.admin.v1.AdminBatchPayoutService",
                        "RetryBatchPayout",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod admin_batch_payout_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with AdminBatchPayoutServiceServer.
    #[async_trait]
    pub trait AdminBatchPayoutService: std::marker::Send + std::marker::Sync + 'static {
        async fn get_batch_payout(
            &self,
            request: tonic::Request<super::GetBatchPayoutRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetBatchPayoutResponse>,
            tonic::Status,
        >;
        async fn list_batch_payouts(
            &self,
            request: tonic::Request<super::ListBatchPayoutsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListBatchPayoutsResponse>,
            tonic::Status,
        >;
        async fn retry_batch_payout(
            &self,
            request: tonic::Request<super::RetryBatchPayoutRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RetryBatchPayoutResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct AdminBatchPayoutServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> AdminBatchPayoutServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for AdminBatchPayoutServiceServer<T>
    where
        T: AdminBatchPayoutService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/payout.batch_payout.admin.v1.AdminBatchPayoutService/GetBatchPayout" => {
                    #[allow(non_camel_case_types)]
                    struct GetBatchPayoutSvc<T: AdminBatchPayoutService>(pub Arc<T>);
                    impl<
                        T: AdminBatchPayoutService,
                    > tonic::server::UnaryService<super::GetBatchPayoutRequest>
                    for GetBatchPayoutSvc<T> {
                        type Response = super::GetBatchPayoutResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetBatchPayoutRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AdminBatchPayoutService>::get_batch_payout(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetBatchPayoutSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/payout.batch_payout.admin.v1.AdminBatchPayoutService/ListBatchPayouts" => {
                    #[allow(non_camel_case_types)]
                    struct ListBatchPayoutsSvc<T: AdminBatchPayoutService>(pub Arc<T>);
                    impl<
                        T: AdminBatchPayoutService,
                    > tonic::server::UnaryService<super::ListBatchPayoutsRequest>
                    for ListBatchPayoutsSvc<T> {
                        type Response = super::ListBatchPayoutsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListBatchPayoutsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AdminBatchPayoutService>::list_batch_payouts(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListBatchPayoutsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/payout.batch_payout.admin.v1.AdminBatchPayoutService/RetryBatchPayout" => {
                    #[allow(non_camel_case_types)]
                    struct RetryBatchPayoutSvc<T: AdminBatchPayoutService>(pub Arc<T>);
                    impl<
                        T: AdminBatchPayoutService,
                    > tonic::server::UnaryService<super::RetryBatchPayoutRequest>
                    for RetryBatchPayoutSvc<T> {
                        type Response = super::RetryBatchPayoutResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RetryBatchPayoutRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AdminBatchPayoutService>::retry_batch_payout(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RetryBatchPayoutSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for AdminBatchPayoutServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "payout.batch_payout.admin.v1.AdminBatchPayoutService";
    impl<T> tonic::server::NamedService for AdminBatchPayoutServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
