// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PayoutCreated {
    #[prost(message, optional, tag = "1")]
    pub amount: ::core::option::Option<super::super::super::shared::types::v1::Money>,
    #[prost(
        enumeration = "super::super::super::shared::enums::v1::PaymentCurrency",
        tag = "2"
    )]
    pub payment_currency: i32,
}
impl ::prost::Name for PayoutCreated {
    const NAME: &'static str = "PayoutCreated";
    const PACKAGE: &'static str = "payout.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "payout.events.v1.PayoutCreated".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/payout.events.v1.PayoutCreated".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PayoutProcessing {}
impl ::prost::Name for PayoutProcessing {
    const NAME: &'static str = "PayoutProcessing";
    const PACKAGE: &'static str = "payout.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "payout.events.v1.PayoutProcessing".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/payout.events.v1.PayoutProcessing".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PayoutSettled {
    #[prost(message, repeated, tag = "1")]
    pub transactions: ::prost::alloc::vec::Vec<payout_settled::PayoutTransaction>,
}
/// Nested message and enum types in `PayoutSettled`.
pub mod payout_settled {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct PayoutTransaction {
        #[prost(message, optional, tag = "1")]
        pub amount: ::core::option::Option<
            super::super::super::super::shared::types::v1::Money,
        >,
        #[prost(
            enumeration = "super::super::super::super::shared::enums::v1::PaymentCurrency",
            tag = "2"
        )]
        pub payment_currency: i32,
        #[prost(
            enumeration = "super::super::super::shared::v1::PayoutReason",
            tag = "3"
        )]
        pub reason: i32,
    }
    impl ::prost::Name for PayoutTransaction {
        const NAME: &'static str = "PayoutTransaction";
        const PACKAGE: &'static str = "payout.events.v1";
        fn full_name() -> ::prost::alloc::string::String {
            "payout.events.v1.PayoutSettled.PayoutTransaction".into()
        }
        fn type_url() -> ::prost::alloc::string::String {
            "/payout.events.v1.PayoutSettled.PayoutTransaction".into()
        }
    }
}
impl ::prost::Name for PayoutSettled {
    const NAME: &'static str = "PayoutSettled";
    const PACKAGE: &'static str = "payout.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "payout.events.v1.PayoutSettled".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/payout.events.v1.PayoutSettled".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PayoutFailed {
    #[prost(string, tag = "1")]
    pub failure_code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub failure_reason: ::prost::alloc::string::String,
}
impl ::prost::Name for PayoutFailed {
    const NAME: &'static str = "PayoutFailed";
    const PACKAGE: &'static str = "payout.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "payout.events.v1.PayoutFailed".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/payout.events.v1.PayoutFailed".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PayoutEventEnvelope {
    #[prost(message, optional, tag = "1")]
    pub meta: ::core::option::Option<
        super::super::super::shared::events::v1::EventMetadata,
    >,
    #[prost(string, tag = "2")]
    pub payout_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub reference_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub store_id: ::prost::alloc::string::String,
    #[prost(enumeration = "super::super::payout::merchant::v1::PayoutKind", tag = "5")]
    pub kind: i32,
    #[prost(oneof = "payout_event_envelope::Event", tags = "10, 11, 12, 13")]
    pub event: ::core::option::Option<payout_event_envelope::Event>,
}
/// Nested message and enum types in `PayoutEventEnvelope`.
pub mod payout_event_envelope {
    #[derive(serde::Serialize, serde::Deserialize)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "10")]
        Created(super::PayoutCreated),
        #[prost(message, tag = "11")]
        Processing(super::PayoutProcessing),
        #[prost(message, tag = "12")]
        Settled(super::PayoutSettled),
        #[prost(message, tag = "13")]
        Failed(super::PayoutFailed),
    }
}
impl ::prost::Name for PayoutEventEnvelope {
    const NAME: &'static str = "PayoutEventEnvelope";
    const PACKAGE: &'static str = "payout.events.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "payout.events.v1.PayoutEventEnvelope".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/payout.events.v1.PayoutEventEnvelope".into()
    }
}
