// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum VerificationMethod {
    Unspecified = 0,
    Email = 1,
    Totp = 2,
}
impl VerificationMethod {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "VERIFICATION_METHOD_UNSPECIFIED",
            Self::Email => "VERIFICATION_METHOD_EMAIL",
            Self::Totp => "VERIFICATION_METHOD_TOTP",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VERIFICATION_METHOD_UNSPECIFIED" => Some(Self::Unspecified),
            "VERIFICATION_METHOD_EMAIL" => Some(Self::Email),
            "VERIFICATION_METHOD_TOTP" => Some(Self::Totp),
            _ => None,
        }
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Chain {
    Unspecified = 0,
    Tron = 1,
    BinanceSmartChain = 2,
    Ethereum = 3,
    Polygon = 4,
    Bitcoin = 5,
    Litecoin = 6,
    Solana = 7,
}
impl Chain {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CHAIN_UNSPECIFIED",
            Self::Tron => "CHAIN_TRON",
            Self::BinanceSmartChain => "CHAIN_BINANCE_SMART_CHAIN",
            Self::Ethereum => "CHAIN_ETHEREUM",
            Self::Polygon => "CHAIN_POLYGON",
            Self::Bitcoin => "CHAIN_BITCOIN",
            Self::Litecoin => "CHAIN_LITECOIN",
            Self::Solana => "CHAIN_SOLANA",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CHAIN_UNSPECIFIED" => Some(Self::Unspecified),
            "CHAIN_TRON" => Some(Self::Tron),
            "CHAIN_BINANCE_SMART_CHAIN" => Some(Self::BinanceSmartChain),
            "CHAIN_ETHEREUM" => Some(Self::Ethereum),
            "CHAIN_POLYGON" => Some(Self::Polygon),
            "CHAIN_BITCOIN" => Some(Self::Bitcoin),
            "CHAIN_LITECOIN" => Some(Self::Litecoin),
            "CHAIN_SOLANA" => Some(Self::Solana),
            _ => None,
        }
    }
}
