// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct User {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub avatar_url: ::core::option::Option<::prost::alloc::string::String>,
}
impl ::prost::Name for User {
    const NAME: &'static str = "User";
    const PACKAGE: &'static str = "shared.admin.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "shared.admin.v1.User".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/shared.admin.v1.User".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Store {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub logo: ::core::option::Option<::prost::alloc::string::String>,
}
impl ::prost::Name for Store {
    const NAME: &'static str = "Store";
    const PACKAGE: &'static str = "shared.admin.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "shared.admin.v1.Store".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/shared.admin.v1.Store".into()
    }
}
