// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StoreCurrency {
    #[prost(
        enumeration = "super::super::super::super::shared::enums::v1::PaymentCurrency",
        tag = "1"
    )]
    pub currency: i32,
    #[prost(
        enumeration = "super::super::super::super::shared::enums::v1::NetworkId",
        tag = "2"
    )]
    pub network_id: i32,
    #[prost(string, optional, tag = "3")]
    pub payment_markup: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub payment_tolerance: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "5")]
    pub created_at: ::core::option::Option<::pbjson_types::Timestamp>,
    #[prost(message, optional, tag = "6")]
    pub updated_at: ::core::option::Option<::pbjson_types::Timestamp>,
}
impl ::prost::Name for StoreCurrency {
    const NAME: &'static str = "StoreCurrency";
    const PACKAGE: &'static str = "store.store_currency.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "store.store_currency.merchant.v1.StoreCurrency".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/store.store_currency.merchant.v1.StoreCurrency".into()
    }
}
/// ====== GetStoreCurrency ======
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetStoreCurrencyRequest {
    #[prost(string, tag = "1")]
    pub store_id: ::prost::alloc::string::String,
    #[prost(
        enumeration = "super::super::super::super::shared::enums::v1::PaymentCurrency",
        tag = "2"
    )]
    pub currency: i32,
    #[prost(
        enumeration = "super::super::super::super::shared::enums::v1::NetworkId",
        tag = "3"
    )]
    pub network_id: i32,
}
impl ::prost::Name for GetStoreCurrencyRequest {
    const NAME: &'static str = "GetStoreCurrencyRequest";
    const PACKAGE: &'static str = "store.store_currency.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "store.store_currency.merchant.v1.GetStoreCurrencyRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/store.store_currency.merchant.v1.GetStoreCurrencyRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetStoreCurrencyResponse {
    #[prost(message, optional, tag = "1")]
    pub store_currency: ::core::option::Option<StoreCurrency>,
}
impl ::prost::Name for GetStoreCurrencyResponse {
    const NAME: &'static str = "GetStoreCurrencyResponse";
    const PACKAGE: &'static str = "store.store_currency.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "store.store_currency.merchant.v1.GetStoreCurrencyResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/store.store_currency.merchant.v1.GetStoreCurrencyResponse".into()
    }
}
/// ====== ListStoreCurrencies ======
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListStoreCurrenciesRequest {
    #[prost(string, tag = "1")]
    pub store_id: ::prost::alloc::string::String,
}
impl ::prost::Name for ListStoreCurrenciesRequest {
    const NAME: &'static str = "ListStoreCurrenciesRequest";
    const PACKAGE: &'static str = "store.store_currency.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "store.store_currency.merchant.v1.ListStoreCurrenciesRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/store.store_currency.merchant.v1.ListStoreCurrenciesRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListStoreCurrenciesResponse {
    #[prost(message, repeated, tag = "1")]
    pub store_currencies: ::prost::alloc::vec::Vec<StoreCurrency>,
}
impl ::prost::Name for ListStoreCurrenciesResponse {
    const NAME: &'static str = "ListStoreCurrenciesResponse";
    const PACKAGE: &'static str = "store.store_currency.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "store.store_currency.merchant.v1.ListStoreCurrenciesResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/store.store_currency.merchant.v1.ListStoreCurrenciesResponse".into()
    }
}
/// ====== CreateStoreCurrency ======
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateStoreCurrencyRequest {
    #[prost(string, tag = "1")]
    pub store_id: ::prost::alloc::string::String,
    #[prost(
        enumeration = "super::super::super::super::shared::enums::v1::PaymentCurrency",
        tag = "2"
    )]
    pub currency: i32,
    #[prost(
        enumeration = "super::super::super::super::shared::enums::v1::NetworkId",
        tag = "3"
    )]
    pub network_id: i32,
    #[prost(string, optional, tag = "4")]
    pub payment_markup: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub payment_tolerance: ::core::option::Option<::prost::alloc::string::String>,
}
impl ::prost::Name for CreateStoreCurrencyRequest {
    const NAME: &'static str = "CreateStoreCurrencyRequest";
    const PACKAGE: &'static str = "store.store_currency.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "store.store_currency.merchant.v1.CreateStoreCurrencyRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/store.store_currency.merchant.v1.CreateStoreCurrencyRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateStoreCurrencyResponse {
    #[prost(message, optional, tag = "2")]
    pub store_currency: ::core::option::Option<StoreCurrency>,
}
impl ::prost::Name for CreateStoreCurrencyResponse {
    const NAME: &'static str = "CreateStoreCurrencyResponse";
    const PACKAGE: &'static str = "store.store_currency.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "store.store_currency.merchant.v1.CreateStoreCurrencyResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/store.store_currency.merchant.v1.CreateStoreCurrencyResponse".into()
    }
}
/// ====== UpdateStoreCurrency ======
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateStoreCurrencyRequest {
    #[prost(string, tag = "1")]
    pub store_id: ::prost::alloc::string::String,
    #[prost(
        enumeration = "super::super::super::super::shared::enums::v1::PaymentCurrency",
        tag = "2"
    )]
    pub currency: i32,
    #[prost(
        enumeration = "super::super::super::super::shared::enums::v1::NetworkId",
        tag = "3"
    )]
    pub network_id: i32,
    #[prost(string, optional, tag = "4")]
    pub payment_markup: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub payment_tolerance: ::core::option::Option<::prost::alloc::string::String>,
}
impl ::prost::Name for UpdateStoreCurrencyRequest {
    const NAME: &'static str = "UpdateStoreCurrencyRequest";
    const PACKAGE: &'static str = "store.store_currency.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "store.store_currency.merchant.v1.UpdateStoreCurrencyRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/store.store_currency.merchant.v1.UpdateStoreCurrencyRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateStoreCurrencyResponse {
    #[prost(message, optional, tag = "2")]
    pub store_currency: ::core::option::Option<StoreCurrency>,
}
impl ::prost::Name for UpdateStoreCurrencyResponse {
    const NAME: &'static str = "UpdateStoreCurrencyResponse";
    const PACKAGE: &'static str = "store.store_currency.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "store.store_currency.merchant.v1.UpdateStoreCurrencyResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/store.store_currency.merchant.v1.UpdateStoreCurrencyResponse".into()
    }
}
/// ====== DeleteStoreCurrency ======
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteStoreCurrencyRequest {
    #[prost(string, tag = "1")]
    pub store_id: ::prost::alloc::string::String,
    #[prost(
        enumeration = "super::super::super::super::shared::enums::v1::PaymentCurrency",
        tag = "2"
    )]
    pub currency: i32,
    #[prost(
        enumeration = "super::super::super::super::shared::enums::v1::NetworkId",
        tag = "3"
    )]
    pub network_id: i32,
}
impl ::prost::Name for DeleteStoreCurrencyRequest {
    const NAME: &'static str = "DeleteStoreCurrencyRequest";
    const PACKAGE: &'static str = "store.store_currency.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "store.store_currency.merchant.v1.DeleteStoreCurrencyRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/store.store_currency.merchant.v1.DeleteStoreCurrencyRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteStoreCurrencyResponse {}
impl ::prost::Name for DeleteStoreCurrencyResponse {
    const NAME: &'static str = "DeleteStoreCurrencyResponse";
    const PACKAGE: &'static str = "store.store_currency.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "store.store_currency.merchant.v1.DeleteStoreCurrencyResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/store.store_currency.merchant.v1.DeleteStoreCurrencyResponse".into()
    }
}
/// Generated client implementations.
pub mod merchant_store_currency_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct MerchantStoreCurrencyServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl MerchantStoreCurrencyServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> MerchantStoreCurrencyServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> MerchantStoreCurrencyServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            MerchantStoreCurrencyServiceClient::new(
                InterceptedService::new(inner, interceptor),
            )
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn get_store_currency(
            &mut self,
            request: impl tonic::IntoRequest<super::GetStoreCurrencyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetStoreCurrencyResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/store.store_currency.merchant.v1.MerchantStoreCurrencyService/GetStoreCurrency",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "store.store_currency.merchant.v1.MerchantStoreCurrencyService",
                        "GetStoreCurrency",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_store_currencies(
            &mut self,
            request: impl tonic::IntoRequest<super::ListStoreCurrenciesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListStoreCurrenciesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/store.store_currency.merchant.v1.MerchantStoreCurrencyService/ListStoreCurrencies",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "store.store_currency.merchant.v1.MerchantStoreCurrencyService",
                        "ListStoreCurrencies",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn create_store_currency(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateStoreCurrencyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateStoreCurrencyResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/store.store_currency.merchant.v1.MerchantStoreCurrencyService/CreateStoreCurrency",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "store.store_currency.merchant.v1.MerchantStoreCurrencyService",
                        "CreateStoreCurrency",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_store_currency(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateStoreCurrencyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateStoreCurrencyResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/store.store_currency.merchant.v1.MerchantStoreCurrencyService/UpdateStoreCurrency",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "store.store_currency.merchant.v1.MerchantStoreCurrencyService",
                        "UpdateStoreCurrency",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn delete_store_currency(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteStoreCurrencyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteStoreCurrencyResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/store.store_currency.merchant.v1.MerchantStoreCurrencyService/DeleteStoreCurrency",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "store.store_currency.merchant.v1.MerchantStoreCurrencyService",
                        "DeleteStoreCurrency",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod merchant_store_currency_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with MerchantStoreCurrencyServiceServer.
    #[async_trait]
    pub trait MerchantStoreCurrencyService: std::marker::Send + std::marker::Sync + 'static {
        async fn get_store_currency(
            &self,
            request: tonic::Request<super::GetStoreCurrencyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetStoreCurrencyResponse>,
            tonic::Status,
        >;
        async fn list_store_currencies(
            &self,
            request: tonic::Request<super::ListStoreCurrenciesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListStoreCurrenciesResponse>,
            tonic::Status,
        >;
        async fn create_store_currency(
            &self,
            request: tonic::Request<super::CreateStoreCurrencyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateStoreCurrencyResponse>,
            tonic::Status,
        >;
        async fn update_store_currency(
            &self,
            request: tonic::Request<super::UpdateStoreCurrencyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateStoreCurrencyResponse>,
            tonic::Status,
        >;
        async fn delete_store_currency(
            &self,
            request: tonic::Request<super::DeleteStoreCurrencyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteStoreCurrencyResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct MerchantStoreCurrencyServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> MerchantStoreCurrencyServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for MerchantStoreCurrencyServiceServer<T>
    where
        T: MerchantStoreCurrencyService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/store.store_currency.merchant.v1.MerchantStoreCurrencyService/GetStoreCurrency" => {
                    #[allow(non_camel_case_types)]
                    struct GetStoreCurrencySvc<T: MerchantStoreCurrencyService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: MerchantStoreCurrencyService,
                    > tonic::server::UnaryService<super::GetStoreCurrencyRequest>
                    for GetStoreCurrencySvc<T> {
                        type Response = super::GetStoreCurrencyResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetStoreCurrencyRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MerchantStoreCurrencyService>::get_store_currency(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetStoreCurrencySvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/store.store_currency.merchant.v1.MerchantStoreCurrencyService/ListStoreCurrencies" => {
                    #[allow(non_camel_case_types)]
                    struct ListStoreCurrenciesSvc<T: MerchantStoreCurrencyService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: MerchantStoreCurrencyService,
                    > tonic::server::UnaryService<super::ListStoreCurrenciesRequest>
                    for ListStoreCurrenciesSvc<T> {
                        type Response = super::ListStoreCurrenciesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListStoreCurrenciesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MerchantStoreCurrencyService>::list_store_currencies(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListStoreCurrenciesSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/store.store_currency.merchant.v1.MerchantStoreCurrencyService/CreateStoreCurrency" => {
                    #[allow(non_camel_case_types)]
                    struct CreateStoreCurrencySvc<T: MerchantStoreCurrencyService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: MerchantStoreCurrencyService,
                    > tonic::server::UnaryService<super::CreateStoreCurrencyRequest>
                    for CreateStoreCurrencySvc<T> {
                        type Response = super::CreateStoreCurrencyResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateStoreCurrencyRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MerchantStoreCurrencyService>::create_store_currency(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateStoreCurrencySvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/store.store_currency.merchant.v1.MerchantStoreCurrencyService/UpdateStoreCurrency" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateStoreCurrencySvc<T: MerchantStoreCurrencyService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: MerchantStoreCurrencyService,
                    > tonic::server::UnaryService<super::UpdateStoreCurrencyRequest>
                    for UpdateStoreCurrencySvc<T> {
                        type Response = super::UpdateStoreCurrencyResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UpdateStoreCurrencyRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MerchantStoreCurrencyService>::update_store_currency(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdateStoreCurrencySvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/store.store_currency.merchant.v1.MerchantStoreCurrencyService/DeleteStoreCurrency" => {
                    #[allow(non_camel_case_types)]
                    struct DeleteStoreCurrencySvc<T: MerchantStoreCurrencyService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: MerchantStoreCurrencyService,
                    > tonic::server::UnaryService<super::DeleteStoreCurrencyRequest>
                    for DeleteStoreCurrencySvc<T> {
                        type Response = super::DeleteStoreCurrencyResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeleteStoreCurrencyRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MerchantStoreCurrencyService>::delete_store_currency(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeleteStoreCurrencySvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for MerchantStoreCurrencyServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "store.store_currency.merchant.v1.MerchantStoreCurrencyService";
    impl<T> tonic::server::NamedService for MerchantStoreCurrencyServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
