// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetStoreMemberRequest {
    #[prost(string, tag = "1")]
    pub store_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub member_id: ::prost::alloc::string::String,
}
impl ::prost::Name for GetStoreMemberRequest {
    const NAME: &'static str = "GetStoreMemberRequest";
    const PACKAGE: &'static str = "store.member.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "store.member.merchant.v1.GetStoreMemberRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/store.member.merchant.v1.GetStoreMemberRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetStoreMemberResponse {
    #[prost(message, optional, tag = "1")]
    pub member: ::core::option::Option<super::super::shared::v1::StoreMember>,
}
impl ::prost::Name for GetStoreMemberResponse {
    const NAME: &'static str = "GetStoreMemberResponse";
    const PACKAGE: &'static str = "store.member.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "store.member.merchant.v1.GetStoreMemberResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/store.member.merchant.v1.GetStoreMemberResponse".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListStoreMembersRequest {
    #[prost(string, tag = "1")]
    pub store_id: ::prost::alloc::string::String,
    #[prost(
        enumeration = "super::super::shared::v1::StoreMemberStatus",
        optional,
        tag = "2"
    )]
    pub status: ::core::option::Option<i32>,
}
impl ::prost::Name for ListStoreMembersRequest {
    const NAME: &'static str = "ListStoreMembersRequest";
    const PACKAGE: &'static str = "store.member.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "store.member.merchant.v1.ListStoreMembersRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/store.member.merchant.v1.ListStoreMembersRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListStoreMembersResponse {
    #[prost(message, repeated, tag = "1")]
    pub members: ::prost::alloc::vec::Vec<super::super::shared::v1::StoreMember>,
}
impl ::prost::Name for ListStoreMembersResponse {
    const NAME: &'static str = "ListStoreMembersResponse";
    const PACKAGE: &'static str = "store.member.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "store.member.merchant.v1.ListStoreMembersResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/store.member.merchant.v1.ListStoreMembersResponse".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChangeStoreMemberRoleRequest {
    #[prost(string, tag = "1")]
    pub store_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub member_id: ::prost::alloc::string::String,
    #[prost(enumeration = "super::super::shared::v1::StoreMemberRole", tag = "3")]
    pub role: i32,
}
impl ::prost::Name for ChangeStoreMemberRoleRequest {
    const NAME: &'static str = "ChangeStoreMemberRoleRequest";
    const PACKAGE: &'static str = "store.member.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "store.member.merchant.v1.ChangeStoreMemberRoleRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/store.member.merchant.v1.ChangeStoreMemberRoleRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChangeStoreMemberRoleResponse {
    #[prost(message, optional, tag = "1")]
    pub member: ::core::option::Option<super::super::shared::v1::StoreMember>,
}
impl ::prost::Name for ChangeStoreMemberRoleResponse {
    const NAME: &'static str = "ChangeStoreMemberRoleResponse";
    const PACKAGE: &'static str = "store.member.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "store.member.merchant.v1.ChangeStoreMemberRoleResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/store.member.merchant.v1.ChangeStoreMemberRoleResponse".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SuspendStoreMemberRequest {
    #[prost(string, tag = "1")]
    pub store_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub member_id: ::prost::alloc::string::String,
}
impl ::prost::Name for SuspendStoreMemberRequest {
    const NAME: &'static str = "SuspendStoreMemberRequest";
    const PACKAGE: &'static str = "store.member.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "store.member.merchant.v1.SuspendStoreMemberRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/store.member.merchant.v1.SuspendStoreMemberRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SuspendStoreMemberResponse {
    #[prost(message, optional, tag = "1")]
    pub member: ::core::option::Option<super::super::shared::v1::StoreMember>,
}
impl ::prost::Name for SuspendStoreMemberResponse {
    const NAME: &'static str = "SuspendStoreMemberResponse";
    const PACKAGE: &'static str = "store.member.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "store.member.merchant.v1.SuspendStoreMemberResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/store.member.merchant.v1.SuspendStoreMemberResponse".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ActivateStoreMemberRequest {
    #[prost(string, tag = "1")]
    pub store_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub member_id: ::prost::alloc::string::String,
}
impl ::prost::Name for ActivateStoreMemberRequest {
    const NAME: &'static str = "ActivateStoreMemberRequest";
    const PACKAGE: &'static str = "store.member.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "store.member.merchant.v1.ActivateStoreMemberRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/store.member.merchant.v1.ActivateStoreMemberRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ActivateStoreMemberResponse {
    #[prost(message, optional, tag = "1")]
    pub member: ::core::option::Option<super::super::shared::v1::StoreMember>,
}
impl ::prost::Name for ActivateStoreMemberResponse {
    const NAME: &'static str = "ActivateStoreMemberResponse";
    const PACKAGE: &'static str = "store.member.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "store.member.merchant.v1.ActivateStoreMemberResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/store.member.merchant.v1.ActivateStoreMemberResponse".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoveStoreMemberRequest {
    #[prost(string, tag = "1")]
    pub store_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub member_id: ::prost::alloc::string::String,
}
impl ::prost::Name for RemoveStoreMemberRequest {
    const NAME: &'static str = "RemoveStoreMemberRequest";
    const PACKAGE: &'static str = "store.member.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "store.member.merchant.v1.RemoveStoreMemberRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/store.member.merchant.v1.RemoveStoreMemberRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoveStoreMemberResponse {
    #[prost(message, optional, tag = "1")]
    pub member: ::core::option::Option<super::super::shared::v1::StoreMember>,
}
impl ::prost::Name for RemoveStoreMemberResponse {
    const NAME: &'static str = "RemoveStoreMemberResponse";
    const PACKAGE: &'static str = "store.member.merchant.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "store.member.merchant.v1.RemoveStoreMemberResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/store.member.merchant.v1.RemoveStoreMemberResponse".into()
    }
}
/// Generated client implementations.
pub mod store_member_merchant_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Merchant-facing service for managing store members.
    #[derive(Debug, Clone)]
    pub struct StoreMemberMerchantServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl StoreMemberMerchantServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> StoreMemberMerchantServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> StoreMemberMerchantServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            StoreMemberMerchantServiceClient::new(
                InterceptedService::new(inner, interceptor),
            )
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Get details of a single store member.
        pub async fn get_store_member(
            &mut self,
            request: impl tonic::IntoRequest<super::GetStoreMemberRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetStoreMemberResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/store.member.merchant.v1.StoreMemberMerchantService/GetStoreMember",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "store.member.merchant.v1.StoreMemberMerchantService",
                        "GetStoreMember",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// List members of a store, optionally filtering by status.
        pub async fn list_store_members(
            &mut self,
            request: impl tonic::IntoRequest<super::ListStoreMembersRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListStoreMembersResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/store.member.merchant.v1.StoreMemberMerchantService/ListStoreMembers",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "store.member.merchant.v1.StoreMemberMerchantService",
                        "ListStoreMembers",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Change the role of an existing store member.
        pub async fn change_store_member_role(
            &mut self,
            request: impl tonic::IntoRequest<super::ChangeStoreMemberRoleRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ChangeStoreMemberRoleResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/store.member.merchant.v1.StoreMemberMerchantService/ChangeStoreMemberRole",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "store.member.merchant.v1.StoreMemberMerchantService",
                        "ChangeStoreMemberRole",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Suspend an active store member.
        pub async fn suspend_store_member(
            &mut self,
            request: impl tonic::IntoRequest<super::SuspendStoreMemberRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SuspendStoreMemberResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/store.member.merchant.v1.StoreMemberMerchantService/SuspendStoreMember",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "store.member.merchant.v1.StoreMemberMerchantService",
                        "SuspendStoreMember",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Activate a suspended store member.
        pub async fn activate_store_member(
            &mut self,
            request: impl tonic::IntoRequest<super::ActivateStoreMemberRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ActivateStoreMemberResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/store.member.merchant.v1.StoreMemberMerchantService/ActivateStoreMember",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "store.member.merchant.v1.StoreMemberMerchantService",
                        "ActivateStoreMember",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Remove a store member from the store.
        pub async fn remove_store_member(
            &mut self,
            request: impl tonic::IntoRequest<super::RemoveStoreMemberRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RemoveStoreMemberResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/store.member.merchant.v1.StoreMemberMerchantService/RemoveStoreMember",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "store.member.merchant.v1.StoreMemberMerchantService",
                        "RemoveStoreMember",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod store_member_merchant_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with StoreMemberMerchantServiceServer.
    #[async_trait]
    pub trait StoreMemberMerchantService: std::marker::Send + std::marker::Sync + 'static {
        /// Get details of a single store member.
        async fn get_store_member(
            &self,
            request: tonic::Request<super::GetStoreMemberRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetStoreMemberResponse>,
            tonic::Status,
        >;
        /// List members of a store, optionally filtering by status.
        async fn list_store_members(
            &self,
            request: tonic::Request<super::ListStoreMembersRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListStoreMembersResponse>,
            tonic::Status,
        >;
        /// Change the role of an existing store member.
        async fn change_store_member_role(
            &self,
            request: tonic::Request<super::ChangeStoreMemberRoleRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ChangeStoreMemberRoleResponse>,
            tonic::Status,
        >;
        /// Suspend an active store member.
        async fn suspend_store_member(
            &self,
            request: tonic::Request<super::SuspendStoreMemberRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SuspendStoreMemberResponse>,
            tonic::Status,
        >;
        /// Activate a suspended store member.
        async fn activate_store_member(
            &self,
            request: tonic::Request<super::ActivateStoreMemberRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ActivateStoreMemberResponse>,
            tonic::Status,
        >;
        /// Remove a store member from the store.
        async fn remove_store_member(
            &self,
            request: tonic::Request<super::RemoveStoreMemberRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RemoveStoreMemberResponse>,
            tonic::Status,
        >;
    }
    /// Merchant-facing service for managing store members.
    #[derive(Debug)]
    pub struct StoreMemberMerchantServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> StoreMemberMerchantServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>>
    for StoreMemberMerchantServiceServer<T>
    where
        T: StoreMemberMerchantService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/store.member.merchant.v1.StoreMemberMerchantService/GetStoreMember" => {
                    #[allow(non_camel_case_types)]
                    struct GetStoreMemberSvc<T: StoreMemberMerchantService>(pub Arc<T>);
                    impl<
                        T: StoreMemberMerchantService,
                    > tonic::server::UnaryService<super::GetStoreMemberRequest>
                    for GetStoreMemberSvc<T> {
                        type Response = super::GetStoreMemberResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetStoreMemberRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StoreMemberMerchantService>::get_store_member(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetStoreMemberSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/store.member.merchant.v1.StoreMemberMerchantService/ListStoreMembers" => {
                    #[allow(non_camel_case_types)]
                    struct ListStoreMembersSvc<T: StoreMemberMerchantService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: StoreMemberMerchantService,
                    > tonic::server::UnaryService<super::ListStoreMembersRequest>
                    for ListStoreMembersSvc<T> {
                        type Response = super::ListStoreMembersResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListStoreMembersRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StoreMemberMerchantService>::list_store_members(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListStoreMembersSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/store.member.merchant.v1.StoreMemberMerchantService/ChangeStoreMemberRole" => {
                    #[allow(non_camel_case_types)]
                    struct ChangeStoreMemberRoleSvc<T: StoreMemberMerchantService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: StoreMemberMerchantService,
                    > tonic::server::UnaryService<super::ChangeStoreMemberRoleRequest>
                    for ChangeStoreMemberRoleSvc<T> {
                        type Response = super::ChangeStoreMemberRoleResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ChangeStoreMemberRoleRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StoreMemberMerchantService>::change_store_member_role(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ChangeStoreMemberRoleSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/store.member.merchant.v1.StoreMemberMerchantService/SuspendStoreMember" => {
                    #[allow(non_camel_case_types)]
                    struct SuspendStoreMemberSvc<T: StoreMemberMerchantService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: StoreMemberMerchantService,
                    > tonic::server::UnaryService<super::SuspendStoreMemberRequest>
                    for SuspendStoreMemberSvc<T> {
                        type Response = super::SuspendStoreMemberResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SuspendStoreMemberRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StoreMemberMerchantService>::suspend_store_member(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SuspendStoreMemberSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/store.member.merchant.v1.StoreMemberMerchantService/ActivateStoreMember" => {
                    #[allow(non_camel_case_types)]
                    struct ActivateStoreMemberSvc<T: StoreMemberMerchantService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: StoreMemberMerchantService,
                    > tonic::server::UnaryService<super::ActivateStoreMemberRequest>
                    for ActivateStoreMemberSvc<T> {
                        type Response = super::ActivateStoreMemberResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ActivateStoreMemberRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StoreMemberMerchantService>::activate_store_member(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ActivateStoreMemberSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/store.member.merchant.v1.StoreMemberMerchantService/RemoveStoreMember" => {
                    #[allow(non_camel_case_types)]
                    struct RemoveStoreMemberSvc<T: StoreMemberMerchantService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: StoreMemberMerchantService,
                    > tonic::server::UnaryService<super::RemoveStoreMemberRequest>
                    for RemoveStoreMemberSvc<T> {
                        type Response = super::RemoveStoreMemberResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RemoveStoreMemberRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StoreMemberMerchantService>::remove_store_member(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RemoveStoreMemberSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for StoreMemberMerchantServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "store.member.merchant.v1.StoreMemberMerchantService";
    impl<T> tonic::server::NamedService for StoreMemberMerchantServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
