// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ticket {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub staff_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag = "4")]
    pub category_id: ::prost::alloc::string::String,
    #[prost(enumeration = "super::super::super::shared::v1::TicketStatus", tag = "5")]
    pub status: i32,
    #[prost(message, optional, tag = "6")]
    pub created_at: ::core::option::Option<::prost_wkt_types::Timestamp>,
    #[prost(message, optional, tag = "7")]
    pub updated_at: ::core::option::Option<::prost_wkt_types::Timestamp>,
    #[prost(message, optional, tag = "8")]
    pub closed_at: ::core::option::Option<::prost_wkt_types::Timestamp>,
    #[prost(message, optional, tag = "9")]
    pub user: ::core::option::Option<
        super::super::super::super::shared::admin::v1::User,
    >,
}
impl ::prost::Name for Ticket {
    const NAME: &'static str = "Ticket";
    const PACKAGE: &'static str = "support.ticket.admin.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "support.ticket.admin.v1.Ticket".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/support.ticket.admin.v1.Ticket".into()
    }
}
/// ======= GetTicket ====== //
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetTicketRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
impl ::prost::Name for GetTicketRequest {
    const NAME: &'static str = "GetTicketRequest";
    const PACKAGE: &'static str = "support.ticket.admin.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "support.ticket.admin.v1.GetTicketRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/support.ticket.admin.v1.GetTicketRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetTicketResponse {
    #[prost(message, optional, tag = "1")]
    pub ticket: ::core::option::Option<Ticket>,
}
impl ::prost::Name for GetTicketResponse {
    const NAME: &'static str = "GetTicketResponse";
    const PACKAGE: &'static str = "support.ticket.admin.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "support.ticket.admin.v1.GetTicketResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/support.ticket.admin.v1.GetTicketResponse".into()
    }
}
/// ======= GetTickets ====== //
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListTicketsRequest {}
impl ::prost::Name for ListTicketsRequest {
    const NAME: &'static str = "ListTicketsRequest";
    const PACKAGE: &'static str = "support.ticket.admin.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "support.ticket.admin.v1.ListTicketsRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/support.ticket.admin.v1.ListTicketsRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTicketsResponse {
    #[prost(message, repeated, tag = "1")]
    pub tickets: ::prost::alloc::vec::Vec<Ticket>,
}
impl ::prost::Name for ListTicketsResponse {
    const NAME: &'static str = "ListTicketsResponse";
    const PACKAGE: &'static str = "support.ticket.admin.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "support.ticket.admin.v1.ListTicketsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/support.ticket.admin.v1.ListTicketsResponse".into()
    }
}
/// ======= CreateTicket ====== //
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateTicketRequest {
    #[prost(string, tag = "1")]
    pub category_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub files: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
impl ::prost::Name for CreateTicketRequest {
    const NAME: &'static str = "CreateTicketRequest";
    const PACKAGE: &'static str = "support.ticket.admin.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "support.ticket.admin.v1.CreateTicketRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/support.ticket.admin.v1.CreateTicketRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateTicketResponse {
    #[prost(message, optional, tag = "2")]
    pub ticket: ::core::option::Option<Ticket>,
}
impl ::prost::Name for CreateTicketResponse {
    const NAME: &'static str = "CreateTicketResponse";
    const PACKAGE: &'static str = "support.ticket.admin.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "support.ticket.admin.v1.CreateTicketResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/support.ticket.admin.v1.CreateTicketResponse".into()
    }
}
/// ======= CloseTicket ====== //
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CloseTicketRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
impl ::prost::Name for CloseTicketRequest {
    const NAME: &'static str = "CloseTicketRequest";
    const PACKAGE: &'static str = "support.ticket.admin.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "support.ticket.admin.v1.CloseTicketRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/support.ticket.admin.v1.CloseTicketRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CloseTicketResponse {}
impl ::prost::Name for CloseTicketResponse {
    const NAME: &'static str = "CloseTicketResponse";
    const PACKAGE: &'static str = "support.ticket.admin.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "support.ticket.admin.v1.CloseTicketResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/support.ticket.admin.v1.CloseTicketResponse".into()
    }
}
/// ======= ReplyTicket ====== //
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplyTicketRequest {
    #[prost(string, tag = "1")]
    pub ticket_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub files: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
impl ::prost::Name for ReplyTicketRequest {
    const NAME: &'static str = "ReplyTicketRequest";
    const PACKAGE: &'static str = "support.ticket.admin.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "support.ticket.admin.v1.ReplyTicketRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/support.ticket.admin.v1.ReplyTicketRequest".into()
    }
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplyTicketResponse {}
impl ::prost::Name for ReplyTicketResponse {
    const NAME: &'static str = "ReplyTicketResponse";
    const PACKAGE: &'static str = "support.ticket.admin.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "support.ticket.admin.v1.ReplyTicketResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/support.ticket.admin.v1.ReplyTicketResponse".into()
    }
}
/// Generated client implementations.
pub mod admin_ticket_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct AdminTicketServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl AdminTicketServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> AdminTicketServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> AdminTicketServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            AdminTicketServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn get_ticket(
            &mut self,
            request: impl tonic::IntoRequest<super::GetTicketRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetTicketResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/support.ticket.admin.v1.AdminTicketService/GetTicket",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "support.ticket.admin.v1.AdminTicketService",
                        "GetTicket",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_tickets(
            &mut self,
            request: impl tonic::IntoRequest<super::ListTicketsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListTicketsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/support.ticket.admin.v1.AdminTicketService/ListTickets",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "support.ticket.admin.v1.AdminTicketService",
                        "ListTickets",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn create_ticket(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateTicketRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateTicketResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/support.ticket.admin.v1.AdminTicketService/CreateTicket",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "support.ticket.admin.v1.AdminTicketService",
                        "CreateTicket",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn close_ticket(
            &mut self,
            request: impl tonic::IntoRequest<super::CloseTicketRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CloseTicketResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/support.ticket.admin.v1.AdminTicketService/CloseTicket",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "support.ticket.admin.v1.AdminTicketService",
                        "CloseTicket",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn reply_ticket(
            &mut self,
            request: impl tonic::IntoRequest<super::ReplyTicketRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ReplyTicketResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/support.ticket.admin.v1.AdminTicketService/ReplyTicket",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "support.ticket.admin.v1.AdminTicketService",
                        "ReplyTicket",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod admin_ticket_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with AdminTicketServiceServer.
    #[async_trait]
    pub trait AdminTicketService: std::marker::Send + std::marker::Sync + 'static {
        async fn get_ticket(
            &self,
            request: tonic::Request<super::GetTicketRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetTicketResponse>,
            tonic::Status,
        >;
        async fn list_tickets(
            &self,
            request: tonic::Request<super::ListTicketsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListTicketsResponse>,
            tonic::Status,
        >;
        async fn create_ticket(
            &self,
            request: tonic::Request<super::CreateTicketRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateTicketResponse>,
            tonic::Status,
        >;
        async fn close_ticket(
            &self,
            request: tonic::Request<super::CloseTicketRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CloseTicketResponse>,
            tonic::Status,
        >;
        async fn reply_ticket(
            &self,
            request: tonic::Request<super::ReplyTicketRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ReplyTicketResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct AdminTicketServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> AdminTicketServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for AdminTicketServiceServer<T>
    where
        T: AdminTicketService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/support.ticket.admin.v1.AdminTicketService/GetTicket" => {
                    #[allow(non_camel_case_types)]
                    struct GetTicketSvc<T: AdminTicketService>(pub Arc<T>);
                    impl<
                        T: AdminTicketService,
                    > tonic::server::UnaryService<super::GetTicketRequest>
                    for GetTicketSvc<T> {
                        type Response = super::GetTicketResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetTicketRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AdminTicketService>::get_ticket(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetTicketSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/support.ticket.admin.v1.AdminTicketService/ListTickets" => {
                    #[allow(non_camel_case_types)]
                    struct ListTicketsSvc<T: AdminTicketService>(pub Arc<T>);
                    impl<
                        T: AdminTicketService,
                    > tonic::server::UnaryService<super::ListTicketsRequest>
                    for ListTicketsSvc<T> {
                        type Response = super::ListTicketsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListTicketsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AdminTicketService>::list_tickets(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListTicketsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/support.ticket.admin.v1.AdminTicketService/CreateTicket" => {
                    #[allow(non_camel_case_types)]
                    struct CreateTicketSvc<T: AdminTicketService>(pub Arc<T>);
                    impl<
                        T: AdminTicketService,
                    > tonic::server::UnaryService<super::CreateTicketRequest>
                    for CreateTicketSvc<T> {
                        type Response = super::CreateTicketResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateTicketRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AdminTicketService>::create_ticket(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateTicketSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/support.ticket.admin.v1.AdminTicketService/CloseTicket" => {
                    #[allow(non_camel_case_types)]
                    struct CloseTicketSvc<T: AdminTicketService>(pub Arc<T>);
                    impl<
                        T: AdminTicketService,
                    > tonic::server::UnaryService<super::CloseTicketRequest>
                    for CloseTicketSvc<T> {
                        type Response = super::CloseTicketResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CloseTicketRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AdminTicketService>::close_ticket(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CloseTicketSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/support.ticket.admin.v1.AdminTicketService/ReplyTicket" => {
                    #[allow(non_camel_case_types)]
                    struct ReplyTicketSvc<T: AdminTicketService>(pub Arc<T>);
                    impl<
                        T: AdminTicketService,
                    > tonic::server::UnaryService<super::ReplyTicketRequest>
                    for ReplyTicketSvc<T> {
                        type Response = super::ReplyTicketResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ReplyTicketRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AdminTicketService>::reply_ticket(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ReplyTicketSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for AdminTicketServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "support.ticket.admin.v1.AdminTicketService";
    impl<T> tonic::server::NamedService for AdminTicketServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
